Fix BATS_ROOT resolution when /bin => /usr/bin
Closes #113. This should be robust enough to handle the /bin => /usr/bin
symlink on CentOS7 as originally reported, but any manner of symlink
chains leading to the `bin/bats` executable in the installation
directory. Maintains portability between `readlink` implementations by
not relying on the GNU-specific `-e` option.

There's no perceptible performance impact.

This renames the original `bats_absolute_path` function to the more
obvious `bats_resolve_absolute_root_dir`, and introduces the
`BATS_MAX_SYMLINKS` variable to ensure symlink resolution short-circuits
in case cycles appear. While this can be user-controlled, I've not
documented it in the README, hoping that no one will need to change the
setting in a real-world situation.

Also tweaks the value of `BATS_TEST_SUITE_TMPDIR` from `tmp` to
`bats-test-tmp` to avoid potential collisions with other `BATS_TMPDIR`
directories.

diff --git a/bin/bats b/bin/bats
--- a/bin/bats
+++ b/bin/bats
@@ -9,27 +9,53 @@ elif command -v 'readlink' >/dev/null; then
   BATS_READLINK='readlink'
 fi
 
+BATS_MAX_SYMLINKS="${BATS_MAX_SYMLINKS:-16}"
+
 bats_resolve_link() {
   if ! "$BATS_READLINK" "$1"; then
     return 0
   fi
 }
 
-bats_absolute_path() {
+bats_resolve_absolute_root_dir() {
   local cwd="$PWD"
   local path="$1"
   local result="$2"
+  local target_dir="${path%/*}"
+  local target_name="${path##*/}"
+  local limit="$BATS_MAX_SYMLINKS"
 
-  while [[ -n "$path" ]]; do
-    cd "${path%/*}"
-    path="$(bats_resolve_link "${path##*/}")"
+  while [[ "$limit" -ne -1 ]]; do
+    target_dir="${path%/*}"
+    target_name="${path##*/}"
+
+    if [[ "$target_dir" != "$path" ]]; then
+      cd "$target_dir"
+    fi
+
+    # Resolve the parent directory, e.g. /bin => /usr/bin on CentOS (#113).
+    while [[ -L "$PWD" && "$((--limit))" -ne -1 ]]; do
+      target_dir="$(bats_resolve_link "$PWD")"
+      if [[ "${target_dir:0:1}" != '/' ]]; then
+        target_dir="$PWD/../$target_dir"
+      fi
+      cd "$target_dir"
+    done
+
+    if [[ ! -L "$target_name" ]]; then
+      printf -v "$result" -- '%s' "${PWD%/*}"
+      cd "$cwd"
+      return
+    elif [[ "$((--limit))" -ne -1 ]]; then
+      path="$(bats_resolve_link "$target_name")"
+    fi
   done
 
-  printf -v "$result" -- '%s' "$PWD"
-  cd "$cwd"
+  printf '%s failed to resolve after following %d symlink(s)\n' \
+    "$0" "$BATS_MAX_SYMLINKS" >&2
+  return 1
 }
 
 export BATS_ROOT
-bats_absolute_path "$0" 'BATS_ROOT'
-BATS_ROOT="${BATS_ROOT%/*}"
+bats_resolve_absolute_root_dir "$0" 'BATS_ROOT'
 exec "$BATS_ROOT/libexec/bats-core/bats" "$@"
