Allow for any two character quote style to be picked up
and fall back to custom with BEGIN/END quote

diff --git a/libexec/bats-core/bats b/libexec/bats-core/bats
--- a/libexec/bats-core/bats
+++ b/libexec/bats-core/bats
@@ -298,28 +298,24 @@ if [[ -n "$report_formatter" ]]; then
   esac
 fi
 
-case ${BATS_CODE_QUOTE_STYLE:-'`'} in
-	"\`'")
-		BATS_BEGIN_CODE_QUOTE='`'
-		BATS_END_CODE_QUOTE="'"
-	;;
-	'``')
-		BATS_BEGIN_CODE_QUOTE='`'
-		BATS_END_CODE_QUOTE='`'
-	;;
-	custom)
-		if [[ ${BATS_BEGIN_CODE_QUOTE-UNSET} == unset
-			|| ${BATS_END_CODE_QUOTE-UNSET} == unset ]]; then
-			printf "ERROR: BATS_CODE_QUOTE_STYLE=custom requires BATS_BEGIN_CODE_QUOTE and BATS_END_CODE_QUOTE to be set\n"
-			exit 1
-		fi
-	;;
-	*)
-		printf "ERROR: Unknown BATS_CODE_QUOTE_STYLE: %s\n" "$BATS_CODE_QUOTE_STYLE"
-		exit 1
-	;;
+case "${BATS_CODE_QUOTE_STYLE-"\`'"}" in
+  ??)
+    BATS_BEGIN_CODE_QUOTE="${BATS_CODE_QUOTE_STYLE::1}"
+    BATS_END_CODE_QUOTE="${BATS_CODE_QUOTE_STYLE:1:1}"
+    export BATS_BEGIN_CODE_QUOTE BATS_END_CODE_QUOTE
+  ;;
+  custom)
+    if [[ ${BATS_BEGIN_CODE_QUOTE-BATS_BEGIN_CODE_QUOTE_UNSET} == BATS_BEGIN_CODE_QUOTE_UNSET 
+        || ${BATS_END_CODE_QUOTE-BATS_BEGIN_CODE_QUOTE_UNSET} == BATS_BEGIN_CODE_QUOTE_UNSET ]]; then
+      printf "ERROR: BATS_CODE_QUOTE_STYLE=custom requires BATS_BEGIN_CODE_QUOTE and BATS_END_CODE_QUOTE to be set\n" >&2
+      exit 1
+    fi
+  ;;
+  *)
+    printf "ERROR: Unknown BATS_CODE_QUOTE_STYLE: %s\n" "$BATS_CODE_QUOTE_STYLE" >&2
+    exit 1
+  ;;
 esac
-export BATS_BEGIN_CODE_QUOTE BATS_END_CODE_QUOTE
 
 if [[ -n "$output" ]]; then
   if [[ ! -w "${output}" ]]; then
