Don't fork test as fast as possible
also print results as early as possible

diff --git a/libexec/bats-core/bats-exec-file b/libexec/bats-core/bats-exec-file
--- a/libexec/bats-core/bats-exec-file
+++ b/libexec/bats-core/bats-exec-file
@@ -134,12 +134,69 @@ function teardown_file() {
   return 0
 }
 
+bats_parallel_exec_test() { # $1 = test_output_dir, the rest is forwarded to bats-exec-test
+  test_output_dir="$1"
+  mkdir -p "$test_output_dir"
+  shift
+
+  # store the pid for waiting on finish
+  printf "%d" "$$" > "$test_output_dir/pid"
+
+  bats-exec-test "$@" 2>"$test_output_dir/stderr" >"$test_output_dir/stdout"
+
+  # store the result for marking end and retrieving errors
+  printf "%d" "$?" > "$test_output_dir/exitcode"
+}
+
+# make visible for GNU parallel
+export -f bats_parallel_exec_test
+
+bats_run_tests_in_parallel() {
+  for test_name in "${tests_to_run[@]}"; do
+    # Only handle non-empty lines
+    if [[ $test_name ]]; then
+      ((++test_number_in_suite))
+      ((++test_number_in_file))
+      # parallelize across files using parallel's semaphore mode
+      # shellcheck disable=SC2154 #bats_parallel_args is inherited from exec-suite
+      parallel --semaphore -j "$num_jobs" "${bats_parallel_args[@]}" -- bats_parallel_exec_test "$output_folder/$test_number_in_suite" "${flags[@]}" "$filename" "$test_name" "$test_number_in_suite" "$test_number_in_file"
+    fi
+  done
+}
+
+# forward the stdin/stderr output of the test with the given number
+# this will block until the test was started and finished before printig anything
+# this will also return the test's exit code
+bats_forward_output_of_test() {
+  test_number="$1"
+  test_output_dir="$output_folder/$test_number"
+  # wait for test to start
+  until [ -e "$test_output_dir/pid" ]
+  do
+    sleep 1
+  done
+  # wait for the test to be finished if it hasn't yet
+  if [[ ! -e "$test_output_dir/exitcode" ]]; then
+    # get the test's pid
+    test_pid=$(cat "$test_output_dir/pid")
+    # GNU parallel semaphore's subprocess will not be our child, 
+    # we cannot use `wait` but we can `tail`!
+    tail --pid="$test_pid" -f /dev/null
+  fi
+  # wait for tests to finish in the order they were started and output their results as they come in
+  cat "$test_output_dir/stdout"
+  # additionally output stderr as parallel does by default
+  cat "$test_output_dir/stderr" >&2
+  # retrieve failure
+  return "$(cat "$test_output_dir/exitcode")"
+}
+
 bats_run_tests() {
   status=0
   tests_to_run=()
   local line_number=0
   # the global test number must be visible to traps -> not local
-  test_number_in_suite=''
+  first_test_number_in_suite=''
   while read -r test_line; do
     test_file=${test_line%%$'\t'*}
     test_name=${test_line##*$'\t'}
@@ -147,43 +204,25 @@ bats_run_tests() {
       tests_to_run+=("$test_name")
       # save the first test's number for later iteration
       # this assumes that tests for a file are stored consecutive in the file!
-      if [[ -z "$test_number_in_suite" ]]; then
-        test_number_in_suite=$line_number
+      if [[ -z "$first_test_number_in_suite" ]]; then
+        first_test_number_in_suite=$line_number
       fi
     fi
     ((++line_number))
   done <"$TESTS_FILE"
 
-  local test_number_in_file=0
+  test_number_in_suite="$first_test_number_in_suite"
+  test_number_in_file=0
   if [[ "$num_jobs" != 1 ]]; then
-    test_pids_and_numbers=()
     output_folder="$BATS_RUN_TMPDIR/parallel_output"
-    for test_name in "${tests_to_run[@]}"; do
-      # Only handle non-empty lines
-      if [[ $test_name ]]; then
-        ((++test_number_in_suite))
-        ((++test_number_in_file))
-        test_output_dir="$output_folder/$test_number_in_suite"
-        mkdir -p "$test_output_dir"
-        # parallelize across files using parallel's semaphore mode
-        # use --results to gather output in separate files
-        # use --fg mode to retrieve exit codes (all non zero exit codes seem to mapped to 1), but which requires us to suppress its output
-        # shellcheck disable=SC2154 #bats_parallel_args is inherited from exec-suite
-        parallel --semaphore -j "$num_jobs" "${bats_parallel_args[@]}" --fg -- bats-exec-test "${flags[@]}" "$filename" "$test_name" "$test_number_in_suite" "$test_number_in_file" >"$test_output_dir/stdout" 2>"$test_output_dir/stderr" &
-        pid=$!
-        test_pids_and_numbers+=("$pid,$test_number_in_suite")
-      fi
-    done
-    for test_pid_and_number in "${test_pids_and_numbers[@]}"; do
-      test_pid=${test_pid_and_number%,*}
-      test_number_in_suite=${test_pid_and_number##*,}
-      test_output_dir="$output_folder/$test_number_in_suite"
-      # fetch the return code
-      wait "$test_pid" || status=1
-      # wait for tests to finish in the order they were started and output their results as they come in
-      cat "$test_output_dir/stdout"
-      # additionally output stderr as parallel does by default
-      cat "$test_output_dir/stderr" >&2
+    # do in background to not block output further down
+    bats_run_tests_in_parallel &
+
+    last_test_number_of_file_in_suite=$(( first_test_number_in_suite + ${#tests_to_run[@]} - 1))
+    # forward the remaining test's outputs in their order
+    # this will block per test until it is finished
+    for number_in_suite_of_test_to_end in $(seq $first_test_number_in_suite $last_test_number_of_file_in_suite); do
+      bats_forward_output_of_test "$((number_in_suite_of_test_to_end+1))" || status=1
     done
   else
     for test_name in "${tests_to_run[@]}"; do
