Unbreak test suites with multiple files loading common constants
Test suites with a helper file with common constants that is loaded by
multiple files stopped working with:
  $ bats /some/path
  /some/path/test_helper.bash: line 1: A_CONSTANT: readonly variable
  Error while sourcing library loader at '/some/path/test_helper.bash'

If the helper file had anything else other than the common constants,
then the tests would run, but the spew about the constants would still
remain:
  $ bats --tap /some/path
  /some/path/test_helper.bash: line 1: A_CONSTANT: readonly variable
  1..2
  ok 1 first
  ok 2 second

Fallout from 9d5ecdbe319bd0e39ef2637806832bb07768fb23

https://github.com/bats-core/bats-core/pull/904

diff --git a/libexec/bats-core/bats-gather-tests b/libexec/bats-core/bats-gather-tests
--- a/libexec/bats-core/bats-gather-tests
+++ b/libexec/bats-core/bats-gather-tests
@@ -271,6 +271,14 @@ trap bats_gather_tests_exit_trap EXIT
 
 bats_set_stacktrace_limit
 
+# override test_functions.bash's version to use it for test registration
+load() {
+  # the standard error stream and exit code will be revealed when running the tests
+  if ! bats_load_safe "$@" 2>/dev/null; then
+    return 0
+  fi
+}
+
 bats_setup_tracing
 focus_mode=0
 for filename in "$@"; do
