WIP

diff --git a/libexec/bats-core/bats-exec-file b/libexec/bats-core/bats-exec-file
--- a/libexec/bats-core/bats-exec-file
+++ b/libexec/bats-core/bats-exec-file
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-set -e
+set -eET
 
 flags=()
 num_jobs=1
@@ -40,27 +40,74 @@ fi
 
 BATS_TEST_FILENAME="$filename"
 
-if [[ -z "$TMPDIR" ]]; then
-BATS_TMPDIR='/tmp'
-else
-BATS_TMPDIR="${TMPDIR%/}"
-fi
-BATS_SUITE_TMPNAME="$BATS_TMPDIR/bats-suite.$$"
-BATS_FILE_OUT="$BATS_SUITE_TMPNAME.out"
+source "$BATS_ROOT/lib/preprocessing.bash"
 
-bats_suite_preprocess_source() {
-    BATS_FILE_TEST_SOURCE="${BATS_SUITE_TMPNAME}.src"
-    bats-preprocess "$1" >"$BATS_FILE_TEST_SOURCE"
-    trap 'bats_suite_cleanup_preprocessed_source' ERR EXIT
-    trap 'bats_suite_cleanup_preprocessed_source; exit 1' INT
+run_setup_file() {
+  source "$BATS_ROOT/lib/tracing.bash"
+  source "$BATS_ROOT/lib/test_functions.bash"
+
+  exec 3<&1
+
+  BATS_STACK_TRACE=()
+  BATS_CURRENT_STACK_TRACE=()
+
+  # these are defined only to avoid errors when referencing undefined variables down the line
+  BATS_TEST_NAME=
+  BATS_TEST_COMPLETED=
+
+  BATS_SETUP_FILE_COMPLETED=
+  BATS_TEARDOWN_FILE_COMPLETED=
+  BATS_ERROR_STATUS=
+  trap 'bats_debug_trap "$BASH_SOURCE"' DEBUG
+  trap 'bats_error_trap' ERR
+  trap 'bats_file_teardown_trap' EXIT
+
+  touch "$BATS_OUT"
+  # get the setup_file/teardown_file functions for this file (if it has them)
+  source "$BATS_TEST_SOURCE"
+  setup_file >>"$BATS_OUT" 2>&1
+
+  BATS_SETUP_FILE_COMPLETED=1
+  trap 'bats_file_exit_trap' EXIT
 }
 
-bats_suite_cleanup_preprocessed_source() {
-    rm -f "$BATS_FILE_TEST_SOURCE"
+run_teardown_file() {
+  teardown_file >>"$BATS_OUT" 2>&1 || status="$?"
+  BATS_TEARDOWN_FILE_COMPLETED=1
 }
 
-bats_file_error_trap() {
-    echo setup_error >&2
+bats_file_teardown_trap() {
+  bats_error_trap
+  local status=0
+  run_teardown_file
+  if [[ $status -eq 0 ]]; then
+    BATS_TEARDOWN_FILE_COMPLETED=1
+  elif [[ -n "$BATS_TEST_COMPLETED" ]]; then
+    BATS_ERROR_STATUS="$status"
+  fi
+
+  bats_file_exit_trap
+}
+
+bats_file_exit_trap() {
+    trap - ERR EXIT
+    if [[ -z "$BATS_SETUP_FILE_COMPLETED" || -z "$BATS_TEARDOWN_FILE_COMPLETED" ]]; then
+      if [[ -z "$BATS_SETUP_FILE_COMPLETED" ]]; then
+        FAILURE_REASON='setup_file'
+      else 
+        FAILURE_REASON='teardown_file'
+      fi
+      printf "not ok %d %s\n" "$(( test_number + 1))" "$FAILURE_REASON failed"
+      bats_print_stack_trace "${BATS_STACK_TRACE[@]}" 
+      bats_print_failed_command 
+      while IFS= read -r line; do
+          printf "# %s\n" "$line"
+      done < "$BATS_OUT" >&3
+      rm -rf "$BATS_OUT"
+      status=1
+    fi
+    bats_cleanup_preprocessed_source
+    exit $status
 }
 
 function setup_file() { 
@@ -69,6 +116,23 @@ function setup_file() {
 
 function teardown_file() { 
     return 0 
+}
+
+run_tests() {
+  status=0
+  tests_to_run=()
+  while read test_name; do
+    tests_to_run+=("$test_name")
+  done < "$TESTS_FILE"
+
+  for test_name in "${tests_to_run[@]}"; do
+      # Only handle non-empty lines
+      if [[ $test_name ]]; then
+          ((++test_number))
+          bats-exec-test "${flags[@]}" "$filename" "$test_name" "$test_number" || status=1
+      fi
+  done
+  export status
 }
 
 # TODO: we want to run setup/teardown file but have following problems
@@ -84,52 +148,9 @@ function teardown_file() {
 # 
 # Running the preprocessing here (using shared code with bats-exec-test) requires us to do the clean up ourselves -> more traps
 
-# get the setup_file/teardown_file functions for this file (if it has them)
-bats_suite_preprocess_source $filename
+bats_preprocess_source $filename
+run_setup_file
+run_tests
+run_teardown_file
 
-source "$BATS_ROOT/lib/tracing.bash"
-source "$BATS_ROOT/lib/test_functions.bash"
-
-exec 3<&1
-
-BATS_STACK_TRACE=()
-BATS_CURRENT_STACK_TRACE=()
-
-BATS_TEST_COMPLETED=
-BATS_TEST_SKIPPED=
-BATS_TEARDOWN_COMPLETED=
-BATS_ERROR_STATUS=
-#trap 'bats_debug_trap "$BASH_SOURCE"' DEBUG
-trap 'bats_file_error_trap' ERR
-#trap 'bats_teardown_trap' EXIT
-
-touch "$BATS_FILE_OUT"
-source "$BATS_FILE_TEST_SOURCE"
-setup_file >>"$BATS_FILE_OUT" 2>&1 && BATS_SETUP_FILE_SUCCESSFUL="$?" 
-
-#trap - EXIT
-if [[ ! $BATS_SETUP_FILE_SUCCESSFUL == "0" ]]; then
-    printf "not ok %d %s\n" "$test_number" "setup_file in $filename" 
-    bats_print_stack_trace "${BATS_STACK_TRACE[@]}" 
-    #bats_print_failed_command 
-    while IFS= read -r line; do
-        printf "# %s\n" "$line"
-    done < "$BATS_FILE_OUT" >&3
-    rm -rf "$BATS_FILE_OUT"
-    exit 1
-fi
-
-status=0
-tests_to_run=()
-while read test_name; do
-  tests_to_run+=("$test_name")
-done < "$TESTS_FILE"
-
-for test_name in "${tests_to_run[@]}"; do
-    # Only handle non-empty lines
-    if [[ $test_name ]]; then
-        ((++test_number))
-        bats-exec-test "${flags[@]}" "$filename" "$test_name" "$test_number" || status=1
-    fi
-done
 exit $status
