Ensure that report-formatter errors are visible

diff --git a/libexec/bats-core/bats b/libexec/bats-core/bats
--- a/libexec/bats-core/bats
+++ b/libexec/bats-core/bats
@@ -482,7 +482,7 @@ set -o pipefail execfail
 # pipe stdin into command and to stdout
 # pipe command stdout to file
 bats_tee() { # <output-file> <command...>
-  local output_file=$1
+  local output_file=$1 status=0
   shift
   exec 3<&1 # use FD3 to get around pipe
   {
@@ -494,7 +494,11 @@ bats_tee() { # <output-file> <command...>
       printf "%s\n" "$line"     # write to command/file
       printf "%s\n" "$line" >&3 # write to our stdout
     fi
-  } | "$@" >"$output_file"
+  } | "$@" >"$output_file" || status=$?
+  if (( status != 0 )); then
+    printf "ERROR: command \`%s\` failed with status %d\n" "$*" "$status" >&2
+  fi
+  return $status
 }
 
 if [[ -n "$report_formatter" ]]; then
