tagging: Add trimming and validity checking

diff --git a/libexec/bats-core/bats-exec-suite b/libexec/bats-core/bats-exec-suite
--- a/libexec/bats-core/bats-exec-suite
+++ b/libexec/bats-core/bats-exec-suite
@@ -154,6 +154,10 @@ bats_gather_tests() {
       fi
       test_names+=("$line")
     done < <(BATS_TEST_FILTER="$filter" bats-preprocess "$filename")
+    
+    if (( $? != 0 )); then
+      abort "Aborted due to preprocessing failure in $filename"
+    fi
 
     if [[ "${#test_dupes[@]}" -ne 0 ]]; then
       abort "Duplicate test name(s) in file \"${filename}\": ${test_dupes[*]}"
diff --git a/libexec/bats-core/bats-preprocess b/libexec/bats-core/bats-preprocess
--- a/libexec/bats-core/bats-preprocess
+++ b/libexec/bats-core/bats-preprocess
@@ -33,16 +33,45 @@ bats_encode_test_name() {
 
 BATS_TEST_PATTERN="^[[:blank:]]*@test[[:blank:]]+(.*[^[:blank:]])[[:blank:]]+\{(.*)\$"
 BATS_TEST_PATTERN_COMMENT="[[:blank:]]*([^[:blank:]()]+)[[:blank:]]*\(?\)?[[:blank:]]+\{[[:blank:]]+#[[:blank:]]*@test[[:blank:]]*\$"
-BATS_COMMENT_COMMAND_PATTERN="^[[:blank:]]*#[[:blank:]]*bats[[:blank:]]*(.*)$"
+BATS_COMMENT_COMMAND_PATTERN="^[[:blank:]]*#[[:blank:]]*bats[[:blank:]]+(.*)$"
+BATS_VALID_TAG_PATTERN="[-_:[:alnum:]]+"
+BATS_VALID_TAGS_PATTERN="^ *($BATS_VALID_TAG_PATTERN)?( *, *$BATS_VALID_TAG_PATTERN)* *$"
 
 source "$BATS_ROOT/lib/bats-core/common.bash"
+
+extract_tags() { # <tag_type/return_var> <tags-string>
+  local -r tag_type=$1 tags_string=$2
+  local -a tags=()
+
+  if [[ $tags_string =~ $BATS_VALID_TAGS_PATTERN ]]; then
+    IFS=, read -ra tags <<< "$tags_string"
+    local -ri length=${#tags[@]}
+    for (( i = 0; i < length; ++i )); do
+      local element="tags[$i]"
+      bats_trim "$element" "${!element}" 2>/dev/null # printf on bash 3 will complain but work anyways
+      if [[ -z "${!element}" && -n "${CHECK_BATS_COMMENT_COMMANDS:-}" ]]; then
+        printf "%s:%d: Error: Invalid %s: '%s'. " "$test_file" "$line_number" "$tag_type" "$tags_string"
+        printf "Tags must not be empty. Please remove redundant commas!\n"
+        exit_code=1
+      fi
+    done
+  elif [[ -n "${CHECK_BATS_COMMENT_COMMANDS:-}" ]]; then
+    printf "%s:%d: Error: Invalid %s: '%s'. " "$test_file" "$line_number" "$tag_type" "$tags_string"
+    printf "Valid tags must match %s and be separated with comma (and optional spaces)\n" "$BATS_VALID_TAG_PATTERN" 
+    exit_code=1
+  fi >&2
+  eval "$tag_type=(\"\${tags[@]}\")"
+}
 
 test_file="$1"
 tests=()
 test_tags=()
 file_tags=()
+line_number=0
+exit_code=0
 {
   while IFS= read -r line; do
+    (( ++line_number ))
     line="${line//$'\r'/}"
     if [[ "$line" =~ $BATS_TEST_PATTERN ]] || [[ "$line" =~ $BATS_TEST_PATTERN_COMMENT ]]; then
       name="${BASH_REMATCH[1]#[\'\"]}"
@@ -62,10 +91,10 @@ file_tags=()
         command=${BASH_REMATCH[1]}
         case $command in 
           'test_tags='*)
-            IFS=, read -ra test_tags <<< "${command#test_tags=}"
+            extract_tags test_tags "${command#test_tags=}"
           ;;
           'file_tags='*)
-            IFS=, read -ra file_tags <<< "${command#file_tags=}"
+            extract_tags file_tags "${command#file_tags=}"
           ;;
         esac
       fi
@@ -77,3 +106,5 @@ file_tags=()
 for test_name in "${tests[@]}"; do
   printf 'bats_test_function %s\n' "$test_name"
 done
+
+exit $exit_code
