feat: add junit formatter

diff --git a/libexec/bats-core/bats b/libexec/bats-core/bats
--- a/libexec/bats-core/bats
+++ b/libexec/bats-core/bats
@@ -26,14 +26,23 @@ Usage: $cmd [-cr] [-f <regex>] [-j <jobs>] [-p | -t] <test>...
   <test> is the path to a Bats test file, or the path to a directory
   containing Bats test files (ending with ".bats").
 
-  -c, --count      Count the number of test cases without running any tests
-  -f, --filter     Filter test cases by names matching the regular expression
-  -h, --help       Display this help message
-  -j, --jobs       Number of parallel jobs to run (requires GNU parallel)
-  -p, --pretty     Show results in pretty format (default for terminals)
-  -r, --recursive  Include tests in subdirectories
-  -t, --tap        Show results in TAP format
-  -v, --version    Display the version number
+  -c, --count               Count the number of test cases without running any tests
+  -f, --filter              Filter test cases by names matching the regular expression
+  -F, --formatter           Switch between formatters (Default: tap, Options: junit, pretty, tap)
+  -h, --help                Display this help message
+  -j, --jobs                Number of parallel jobs to run (requires GNU parallel)
+  --parallel-preserve-environment 
+                   Preserve the environment When running via GNU parallel (run 
+                   \`parallel --record-env\` before!)
+  --no-tempdir-cleanup
+                   Prevent bats from deleting the temporary directory that
+                   contains outputs from the test run
+  -o, --output              A directory to output reports to
+  -p, --pretty              [DEPRECATED] Show results in pretty format (default for terminals), use "--formatter pretty" instead
+  -r, --recursive           Include tests in subdirectories
+  -t, --tap                 [DEPRECATED] Show results in TAP format, use "--formatter tap" instead
+  -T, --timing              Add timing information
+  -v, --version             Display the version number
 
   For more information, see https://github.com/bats-core/bats-core
 
@@ -87,6 +96,13 @@ export BATS_CWD="$PWD"
 export BATS_TEST_PATTERN="^[[:blank:]]*@test[[:blank:]]+(.*[^[:blank:]])[[:blank:]]+\{(.*)\$"
 export BATS_TEST_FILTER=
 export PATH="$BATS_LIBEXEC:$PATH"
+export BATS_ROOT_PID=$$
+if [[ -z "$TMPDIR" ]]; then
+  export BATS_TMPDIR="/tmp"
+else
+  export BATS_TMPDIR="${TMPDIR%/}"
+fi
+export BATS_RUN_TMPDIR="$BATS_TMPDIR/bats-run-$BATS_ROOT_PID"
 
 arguments=()
 
@@ -109,44 +125,74 @@ done
 set -- "${arguments[@]}"
 arguments=()
 
-unset flags pretty recursive
+unset flags recursive formatter_flags
 flags=()
-pretty=
+formatter_flags=()
+formatter='tap'
 recursive=
+tempdir_cleanup=1
+output=
 if [[ -z "${CI:-}" && -t 0 && -t 1 ]] && command -v tput >/dev/null; then
-  pretty=1
+	formatter='pretty'
 fi
 
 while [[ "$#" -ne 0 ]]; do
   case "$1" in
-  -h|--help)
+	-h | --help)
     version
     usage
     exit 0
     ;;
-  -v|--version)
+	-v | --version)
     version
     exit 0
     ;;
-  -c|--count)
+	-c | --count)
     flags+=('-c')
     ;;
-  -f|--filter)
+	-f | --filter)
     shift
     flags+=('-f' "$1")
     ;;
-  -j|--jobs)
+	-F | --formatter)
+		shift
+		if [[ $1 =~ ^(pretty|junit|tap)$ ]]; then
+			formatter="$1"
+		else
+			printf "Unknown formatter '%s', valid options are pretty, junit, tap\n" "$1"
+			exit 1
+		fi
+		;;
+	-o | --output)
     shift
+		output="$1"
+		;;
+	-p | --pretty)
+		formatter='pretty'
+		;;
+	-j | --jobs)
+		shift
     flags+=('-j' "$1")
     ;;
-  -r|--recursive)
+	-r | --recursive)
     recursive=1
     ;;
-  -t|--tap)
-    pretty=
+	-t | --tap)
+		formatter='tap'
     ;;
-  -p|--pretty)
-    pretty=1
+	-T | --timing)
+		flags+=('-T')
+		formatter_flags+=('-T')
+    ;;
+  --parallel-preserve-environment)
+    flags+=("--parallel-preserve-environment")
+    # check if parallel's env setup was run before
+    # will print on stderr and return 255 on failure
+    # suppress stdout (on success)
+    parallel --env _ echo ::: 1 >/dev/null || exit 1
+    ;;
+  --no-tempdir-cleanup)
+    tempdir_cleanup=''
     ;;
   -*)
     abort "Bad command line option '$1'"
@@ -157,6 +203,24 @@ while [[ "$#" -ne 0 ]]; do
   esac
   shift
 done
+
+if [[ -d "$BATS_RUN_TMPDIR" ]]; then
+  printf "Error: BATS_RUN_TMPDIR (%s) already exists\n" "$BATS_RUN_TMPDIR" >&2
+  printf "Reusing old run directories can lead to unexpected results ... aborting!\n" >&2
+  exit 1
+fi
+mkdir -p "$BATS_RUN_TMPDIR"
+if [[ -n "$tempdir_cleanup" ]]; then
+  trap 'rm -rf "$BATS_RUN_TMPDIR"' ERR EXIT
+fi
+
+if [[ "$formatter" != "tap" ]]; then
+	flags+=('-x')
+fi
+if [[ "$formatter" == "junit" ]]; then
+	flags+=('-T')
+	formatter_flags+=('-T')
+fi
 
 if [[ "${#arguments[@]}" -eq 0 ]]; then
   abort 'Must specify at least one <test>'
@@ -183,11 +247,9 @@ for filename in "${arguments[@]}"; do
   fi
 done
 
-formatter="cat"
-if [[ -n "$pretty" ]]; then
-  flags+=("-x")
-  formatter="bats-format-tap-stream"
-fi
+# shellcheck source=lib/bats-core/validator.bash
+source "$BATS_ROOT/lib/bats-core/validator.bash"
 
 set -o pipefail execfail
-exec bats-exec-suite "${flags[@]}" "${filenames[@]}" | "$formatter"
+[[ -n "$output" ]] && export BATS_REPORT_OUTPUT_PATH="$output"
+exec bats-exec-suite "${flags[@]}" "${filenames[@]}" | bats_test_count_validator | "bats-format-$formatter" "${formatter_flags[@]}"
diff --git a/libexec/bats-core/bats-exec-file b/libexec/bats-core/bats-exec-file
--- a/libexec/bats-core/bats-exec-file
+++ b/libexec/bats-core/bats-exec-file
@@ -1,14 +1,15 @@
 #!/usr/bin/env bash
-set -e
+set -eET
 
-flags=()
+export flags=()
 num_jobs=1
 filter=''
+extended_syntax=''
 
 while [[ "$#" -ne 0 ]]; do
   case "$1" in
-  -c)
-    ;;
+  -c) ;;
+
   -f)
     shift
     filter="$1"
@@ -18,9 +19,12 @@ while [[ "$#" -ne 0 ]]; do
     shift
     num_jobs="$1"
     ;;
+  -T)
+    flags+=('-T')
+    ;;
   -x)
-    extended_syntax_flag='-x'
     flags+=('-x')
+	extended_syntax=1
     ;;
   *)
     break
@@ -30,8 +34,7 @@ while [[ "$#" -ne 0 ]]; do
 done
 
 filename=$1
-test_number=$2
-TESTS_FILE="$3"
+TESTS_FILE="$2"
 
 if [[ ! -f "$filename" ]]; then
     printf 'Testfile "%s" not found\n' "$filename" >&2
@@ -40,27 +43,87 @@ fi
 
 BATS_TEST_FILENAME="$filename"
 
-if [[ -z "$TMPDIR" ]]; then
-BATS_TMPDIR='/tmp'
-else
-BATS_TMPDIR="${TMPDIR%/}"
-fi
-BATS_SUITE_TMPNAME="$BATS_TMPDIR/bats-suite.$$"
-BATS_FILE_OUT="$BATS_SUITE_TMPNAME.out"
+# shellcheck source=lib/bats-core/preprocessing.bash
+# shellcheck disable=SC2153
+source "$BATS_ROOT/lib/bats-core/preprocessing.bash"
 
-bats_suite_preprocess_source() {
-    BATS_FILE_TEST_SOURCE="${BATS_SUITE_TMPNAME}.src"
-    bats-preprocess "$1" >"$BATS_FILE_TEST_SOURCE"
-    trap 'bats_suite_cleanup_preprocessed_source' ERR EXIT
-    trap 'bats_suite_cleanup_preprocessed_source; exit 1' INT
+bats_run_setup_file() {
+  # shellcheck source=lib/bats-core/tracing.bash
+	# shellcheck disable=SC2153
+  source "$BATS_ROOT/lib/bats-core/tracing.bash"
+  # shellcheck source=lib/bats-core/test_functions.bash
+	# shellcheck disable=SC2153
+  source "$BATS_ROOT/lib/bats-core/test_functions.bash"
+
+  exec 3<&1
+
+  BATS_STACK_TRACE=()
+  # shellcheck disable=2034
+  BATS_CURRENT_STACK_TRACE=() # used in tracing.bash
+
+  # these are defined only to avoid errors when referencing undefined variables down the line
+  # shellcheck disable=2034
+  BATS_TEST_NAME= # used in tracing.bash
+  # shellcheck disable=2034
+  BATS_TEST_COMPLETED= # used in tracing.bash
+
+  BATS_SETUP_FILE_COMPLETED=
+  BATS_TEARDOWN_FILE_COMPLETED=
+  # shellcheck disable=2034
+  BATS_ERROR_STATUS= # used in tracing.bash
+  trap 'bats_debug_trap "$BASH_SOURCE"' DEBUG
+  trap 'bats_error_trap' ERR
+  trap 'bats_file_teardown_trap' EXIT
+
+  touch "$BATS_OUT"
+  # get the setup_file/teardown_file functions for this file (if it has them)
+  # shellcheck disable=SC1090
+  source "$BATS_TEST_SOURCE"
+  setup_file >>"$BATS_OUT" 2>&1
+
+  BATS_SETUP_FILE_COMPLETED=1
 }
 
-bats_suite_cleanup_preprocessed_source() {
-    rm -f "$BATS_FILE_TEST_SOURCE"
+bats_run_teardown_file() {
+  # avoid running the therdown trap due to errors in teardown_file
+  trap 'bats_file_exit_trap' EXIT
+  local status=0
+  # rely on bats_error_trap to catch failures
+  teardown_file >>"$BATS_OUT" 2>&1 
+
+  BATS_TEARDOWN_FILE_COMPLETED=1
 }
 
-bats_file_error_trap() {
-    echo setup_error >&2
+bats_file_teardown_trap() {
+  bats_error_trap
+  local status=0
+  bats_run_teardown_file
+
+  bats_file_exit_trap
+}
+
+bats_file_exit_trap() {
+    trap - ERR EXIT
+    if [[ -z "$BATS_SETUP_FILE_COMPLETED" || -z "$BATS_TEARDOWN_FILE_COMPLETED" ]]; then
+      if [[ -z "$BATS_SETUP_FILE_COMPLETED" ]]; then
+        FAILURE_REASON='setup_file'
+      else 
+        FAILURE_REASON='teardown_file'
+      fi
+		printf "not ok %d %s\n" "$((test_number + 1))" "$FAILURE_REASON failed" >&3
+      bats_print_stack_trace "${BATS_STACK_TRACE[@]}" >&3
+      bats_print_failed_command >&3
+      while IFS= read -r line; do
+          printf "# %s\n" "$line"
+		done <"$BATS_OUT" >&3
+      if [[ -n "$line" ]]; then
+        printf '# %s\n' "$line"
+      fi
+      rm -rf "$BATS_OUT"
+      status=1
+    fi
+    bats_cleanup_preprocessed_source
+    exit $status
 }
 
 function setup_file() { 
@@ -71,65 +134,75 @@ function teardown_file() {
     return 0 
 }
 
-# TODO: we want to run setup/teardown file but have following problems
-# 1. we need to get their definitions which can only be loaded from the preprocessed file
-# 1.1 the preprocessing is defined in bats-exec-test so we don't have it here
-# 1.2 the load command is also defined in bats-exec-test
-# -> it is preferable to run this from bats-exec-test to avoid duplicating the preprocessing/helper commands
-# 2. we need the file setup to be run only once but its results (e.g. conditionally defined variables) 
-#    might need to be present in all tests of the file, not only the first
-# -> evaluate in suite, so that these results are inherited by the subshells
-# 3. prevent environment changes in sourced test files to leak over into other test files
-# -> each file gets its own context
-# 
-# Running the preprocessing here (using shared code with bats-exec-test) requires us to do the clean up ourselves -> more traps
+bats_run_tests() {
+  status=0
+  tests_to_run=()
+  local line_number=0
+  test_number=''
+  while read -r test_line; do
+    test_file=${test_line%%$'\t'*}
+    test_name=${test_line##*$'\t'}
+    if [[ "$test_file" == "$filename" ]]; then
+      tests_to_run+=("$test_name")
+      # save the first test's number for later iteration
+      # this assumes that tests for a file are stored consecutive in the file!
+      if [[ -z $test_number ]]; then
+        test_number=$line_number
+      fi
+    fi
+    (( ++line_number ))
+  done < "$TESTS_FILE"
 
-# get the setup_file/teardown_file functions for this file (if it has them)
-bats_suite_preprocess_source $filename
+  if [[ "$num_jobs" != 1 ]]; then
+    test_pids_and_numbers=()
+    output_folder="$BATS_RUN_TMPDIR/parallel_output"
+    for test_name in "${tests_to_run[@]}"; do
+      # Only handle non-empty lines
+      if [[ $test_name ]]; then
+        ((++test_number))
+        # parallelize across files using parallel's semaphore mode
+        # use --results to gather output in separate files
+        # use --fg mode to retrieve exit codes (all non zero exit codes seem to mapped to 1), but which requires us to suppress its output
+        # shellcheck disable=SC2154 #bats_parallel_args is inherited from exec-suite
+        parallel --semaphore -j "$num_jobs" "${bats_parallel_args[@]}" --fg --results "$output_folder/$test_number/{}" -- bats-exec-test "${flags[@]}" "$filename" "$test_name" "$test_number" 2>/dev/null >/dev/null &
+        pid=$!
+        test_pids_and_numbers+=("$pid,$test_number")
+      fi
+    done
+    for test_pid_and_number in "${test_pids_and_numbers[@]}"; do
+      test_pid=${test_pid_and_number%,*}
+      test_number=${test_pid_and_number##*,}
+      test_output_dir="$output_folder/$test_number"
+      # fetch the return code
+      wait "$test_pid" || status=1
+      # wait for tests to finish in the order they were started and output their results as they come in
+      cat "$test_output_dir/stdout"
+      # additionally output stderr as parallel does by default
+      cat "$test_output_dir/stderr" >&2
+    done
+  else
+    for test_name in "${tests_to_run[@]}"; do
+        # Only handle non-empty lines
+        if [[ $test_name ]]; then
+            ((++test_number))
+            if [[ "${#flags[@]}" -gt 0 ]]; then
+              bats-exec-test "${flags[@]}" "$filename" "$test_name" "$test_number" || status=1
+            else
+              bats-exec-test "$filename" "$test_name" "$test_number" || status=1
+            fi
+        fi
+    done
+  fi
+  export status
+}
 
-source "$BATS_ROOT/lib/tracing.bash"
-source "$BATS_ROOT/lib/test_functions.bash"
-
-exec 3<&1
-
-BATS_STACK_TRACE=()
-BATS_CURRENT_STACK_TRACE=()
-
-BATS_TEST_COMPLETED=
-BATS_TEST_SKIPPED=
-BATS_TEARDOWN_COMPLETED=
-BATS_ERROR_STATUS=
-#trap 'bats_debug_trap "$BASH_SOURCE"' DEBUG
-trap 'bats_file_error_trap' ERR
-#trap 'bats_teardown_trap' EXIT
-
-touch "$BATS_FILE_OUT"
-source "$BATS_FILE_TEST_SOURCE"
-setup_file >>"$BATS_FILE_OUT" 2>&1 && BATS_SETUP_FILE_SUCCESSFUL="$?" 
-
-#trap - EXIT
-if [[ ! $BATS_SETUP_FILE_SUCCESSFUL == "0" ]]; then
-    printf "not ok %d %s\n" "$test_number" "setup_file in $filename" 
-    bats_print_stack_trace "${BATS_STACK_TRACE[@]}" 
-    #bats_print_failed_command 
-    while IFS= read -r line; do
-        printf "# %s\n" "$line"
-    done < "$BATS_FILE_OUT" >&3
-    rm -rf "$BATS_FILE_OUT"
-    exit 1
+if [[ -n "$extended_syntax" ]]; then
+	printf "suite %s\n" "$(basename $filename)"
 fi
 
-status=0
-tests_to_run=()
-while read test_name; do
-  tests_to_run+=("$test_name")
-done < "$TESTS_FILE"
+bats_preprocess_source "$filename"
+bats_run_setup_file
+bats_run_tests
+bats_run_teardown_file
 
-for test_name in "${tests_to_run[@]}"; do
-    # Only handle non-empty lines
-    if [[ $test_name ]]; then
-        ((++test_number))
-        bats-exec-test "${flags[@]}" "$filename" "$test_name" "$test_number" || status=1
-    fi
-done
 exit $status
