Add --rerun-failed

diff --git a/libexec/bats-core/bats-exec-suite b/libexec/bats-core/bats-exec-suite
--- a/libexec/bats-core/bats-exec-suite
+++ b/libexec/bats-core/bats-exec-suite
@@ -6,6 +6,7 @@ filter=''
 num_jobs=${BATS_NUMBER_OF_PARALLEL_JOBS:-1}
 bats_no_parallelize_across_files=${BATS_NO_PARALLELIZE_ACROSS_FILES-}
 bats_no_parallelize_within_files=
+bats_rerun_failed=
 flags=('--dummy-flag') # add a dummy flag to prevent unset varialeb errors on empty array expansion in old bash versions
 setup_suite_file=''
 BATS_TRACE_LEVEL="${BATS_TRACE_LEVEL:-0}"
@@ -42,6 +43,10 @@ while [[ "$#" -ne 0 ]]; do
   --no-parallelize-within-files)
     bats_no_parallelize_within_files=1
     flags+=("--no-parallelize-within-files")
+    ;;
+  --rerun-failed)
+    bats_rerun_failed=1
+    flags+=("--rerun-failed")
     ;;
   --dummy-flag)
     ;;
@@ -86,37 +91,59 @@ fi
 # create a file that contains all (filtered) tests to run from all files
 TESTS_LIST_FILE="${BATS_RUN_TMPDIR}/test_list_file.txt"
 
-all_tests=()
-for filename in "$@"; do
-  if [[ ! -f "$filename" ]]; then
-    abort "Test file \"${filename}\" does not exist"
-  fi
-
-  test_names=()
-  test_dupes=()
-  while read -r line; do
-    if [[ ! "$line" =~ ^bats_test_function\  ]]; then
-      continue
+bats_gather_tests() {
+  all_tests=()
+  for filename in "$@"; do
+    if [[ ! -f "$filename" ]]; then
+      abort "Test file \"${filename}\" does not exist"
     fi
-    line="${line%$'\r'}"
-    line="${line#* }"
-    test_line=$(printf "%s\t%s" "$filename" "$line")
-    all_tests+=("$test_line")
-    printf "%s\n" "$test_line" >>"$TESTS_LIST_FILE"
-    # avoid unbound variable errors on empty array expansion with old bash versions
-    if [[ ${#test_names[@]} -gt 0 && " ${test_names[*]} " == *" $line "* ]]; then
-      test_dupes+=("$line")
-      continue
+
+    test_names=()
+    test_dupes=()
+    while read -r line; do
+      if [[ ! "$line" =~ ^bats_test_function\  ]]; then
+        continue
+      fi
+      line="${line%$'\r'}"
+      line="${line#* }"
+      test_line=$(printf "%s\t%s" "$filename" "$line")
+      all_tests+=("$test_line")
+      printf "%s\n" "$test_line" >>"$TESTS_LIST_FILE"
+      # avoid unbound variable errors on empty array expansion with old bash versions
+      if [[ ${#test_names[@]} -gt 0 && " ${test_names[*]} " == *" $line "* ]]; then
+        test_dupes+=("$line")
+        continue
+      fi
+      test_names+=("$line")
+    done < <(BATS_TEST_FILTER="$filter" bats-preprocess "$filename")
+
+    if [[ "${#test_dupes[@]}" -ne 0 ]]; then
+      abort "Duplicate test name(s) in file \"${filename}\": ${test_dupes[*]}"
     fi
-    test_names+=("$line")
-  done < <(BATS_TEST_FILTER="$filter" bats-preprocess "$filename")
+  done
 
-  if [[ "${#test_dupes[@]}" -ne 0 ]]; then
-    abort "Duplicate test name(s) in file \"${filename}\": ${test_dupes[*]}"
-  fi
-done
+  test_count="${#all_tests[@]}"
+}
 
-test_count="${#all_tests[@]}"
+if [[ -n "$bats_rerun_failed" ]]; then  
+  mkdir -p "$PWD/.bats"
+  export BATS_RERUN_FAILED_FILE="$PWD/.bats/rerun-failed-tests.list"
+  export BATS_RERUN_FAILED_TMPFILE="${BATS_RERUN_FAILED_FILE}.tmp"
+  if [[ -s "$BATS_RERUN_FAILED_FILE" ]]; then
+    test_count="$(wc -l < "$BATS_RERUN_FAILED_FILE")"
+    cp "$BATS_RERUN_FAILED_FILE" "$TESTS_LIST_FILE"
+  elif [[ -f "$BATS_RERUN_FAILED_FILE" ]]; then
+    printf "There where no failed tests in the last recorded run.\n" >&2
+    printf "Delete the file '%s' to run all tests again.\n" "${BATS_RERUN_FAILED_FILE#"$PWD/"}" >&2
+    test_count=0
+  else
+    printf "No recording of previos runs found. Running all tests!\n" >&2
+    bats_gather_tests "$@"
+  fi 
+  : >"$BATS_RERUN_FAILED_TMPFILE" # truncate the file if it exists, else create
+else
+  bats_gather_tests "$@"
+fi
 
 if [[ -n "$count_only_flag" ]]; then
   printf '%d\n' "${test_count}"
@@ -177,6 +204,12 @@ bats_suite_exit_trap() {
   fi
   if [[ ${BATS_INTERRUPTED-NOTSET} != NOTSET ]]; then
     printf "\n# Received SIGINT, aborting ...\n\n"
+  fi
+  
+  if [[ -n "$bats_rerun_failed" && "${BATS_INTERRUPTED-NOTSET}" == NOTSET ]]; then
+    # only overwrite file once we finished with all tests
+    # else we would discard tests when aborting a test run with CTRL+C
+    mv "$BATS_RERUN_FAILED_TMPFILE" "$BATS_RERUN_FAILED_FILE"
   fi
   exit "$bats_exec_suite_status"
 }
