shfmt all the files

diff --git a/libexec/bats-core/bats b/libexec/bats-core/bats
--- a/libexec/bats-core/bats
+++ b/libexec/bats-core/bats
@@ -91,7 +91,10 @@ expand_path() {
   printf -v "$result" '%s/%s' "$dirname" "${path##*/}"
 }
 
-BATS_LIBEXEC="$(cd "$(dirname "$(bats_readlinkf "${BASH_SOURCE[0]}")")"; pwd)"
+BATS_LIBEXEC="$(
+  cd "$(dirname "$(bats_readlinkf "${BASH_SOURCE[0]}")")"
+  pwd
+)"
 export BATS_LIBEXEC
 export BATS_CWD="$PWD"
 export BATS_TEST_FILTER=
@@ -104,10 +107,10 @@ export BATS_GUARANTEED_MINIMUM_VERSION=0.0.0
 export BATS_LIB_PATH=${BATS_LIB_PATH-/usr/lib/bats}
 BATS_REPORT_OUTPUT_DIR=${BATS_REPORT_OUTPUT_DIR-.}
 
-if [[ ! -d "${BATS_TMPDIR}" ]];then
+if [[ ! -d "${BATS_TMPDIR}" ]]; then
   printf "Error: BATS_TMPDIR (%s) does not exist or is not a directory" "${BATS_TMPDIR}" >&2
   exit 1
-elif [[ ! -w "${BATS_TMPDIR}" ]];then
+elif [[ ! -w "${BATS_TMPDIR}" ]]; then
   printf "Error: BATS_TMPDIR (%s) is not writable" "${BATS_TMPDIR}" >&2
   exit 1
 fi
@@ -134,7 +137,7 @@ set -- "${arguments[@]}"
 arguments=()
 
 unset flags recursive formatter_flags
-flags=('--dummy-flag') # add a dummy flag to prevent unset variable errors on empty array expansion in old bash versions
+flags=('--dummy-flag')           # add a dummy flag to prevent unset variable errors on empty array expansion in old bash versions
 formatter_flags=('--dummy-flag') # add a dummy flag to prevent unset variable errors on empty array expansion in old bash versions
 formatter=${BATS_FORMATTER:-'tap'}
 report_formatter=''
@@ -204,8 +207,8 @@ while [[ "$#" -ne 0 ]]; do
     formatter_flags+=('-T')
     ;;
   # this flag is now a no-op, as it is the parallel default
-  --parallel-preserve-environment)
-    ;;
+  --parallel-preserve-environment) ;;
+
   --no-parallelize-across-files)
     flags+=("--no-parallelize-across-files")
     ;;
@@ -250,7 +253,7 @@ while [[ "$#" -ne 0 ]]; do
   --code-quote-style)
     shift
     BATS_CODE_QUOTE_STYLE="$1"
-  ;;
+    ;;
   --filter-status)
     shift
     flags+=('--filter-status' "$1")
@@ -269,16 +272,16 @@ while [[ "$#" -ne 0 ]]; do
   shift
 done
 
-if [[ -n "${BATS_RUN_TMPDIR:-}" ]];then
+if [[ -n "${BATS_RUN_TMPDIR:-}" ]]; then
   if [[ -d "$BATS_RUN_TMPDIR" ]]; then
     printf "Error: BATS_RUN_TMPDIR (%s) already exists\n" "$BATS_RUN_TMPDIR" >&2
     printf "Reusing old run directories can lead to unexpected results ... aborting!\n" >&2
     exit 1
-  elif ! mkdir -p "$BATS_RUN_TMPDIR" ;then
+  elif ! mkdir -p "$BATS_RUN_TMPDIR"; then
     printf "Error: Failed to create BATS_RUN_TMPDIR (%s)\n" "$BATS_RUN_TMPDIR" >&2
     exit 1
   fi
-elif ! BATS_RUN_TMPDIR=$(mktemp -d "${BATS_TMPDIR}/bats-run-XXXXXX");then
+elif ! BATS_RUN_TMPDIR=$(mktemp -d "${BATS_TMPDIR}/bats-run-XXXXXX"); then
   printf "Error: Failed to create BATS_RUN_TMPDIR (%s) with mktemp\n" "${BATS_TMPDIR}/bats-run-XXXXXX" >&2
   exit 1
 fi
@@ -361,15 +364,15 @@ if [[ -n "$report_formatter" ]]; then
   # only set BATS_REPORT_FILENAME if none was given
   if [[ -z "${BATS_REPORT_FILENAME:-}" ]]; then
     case "$report_formatter" in
-      tap|tap13)
-        BATS_REPORT_FILENAME="report.tap"
-        ;;
-      junit)
-        BATS_REPORT_FILENAME="report.xml"
-        ;;
-      *)
-        BATS_REPORT_FILENAME="report.log"
-        ;;
+    tap | tap13)
+      BATS_REPORT_FILENAME="report.tap"
+      ;;
+    junit)
+      BATS_REPORT_FILENAME="report.xml"
+      ;;
+    *)
+      BATS_REPORT_FILENAME="report.log"
+      ;;
     esac
   fi
 fi
@@ -386,21 +389,21 @@ if [[ "${BATS_CODE_QUOTE_STYLE-BATS_CODE_QUOTE_STYLE_UNSET}" == BATS_CODE_QUOTE_
 fi
 
 case "${BATS_CODE_QUOTE_STYLE}" in
-  ??)
-    BATS_BEGIN_CODE_QUOTE="${BATS_CODE_QUOTE_STYLE::1}"
-    BATS_END_CODE_QUOTE="${BATS_CODE_QUOTE_STYLE:1:1}"
-    export BATS_BEGIN_CODE_QUOTE BATS_END_CODE_QUOTE
+??)
+  BATS_BEGIN_CODE_QUOTE="${BATS_CODE_QUOTE_STYLE::1}"
+  BATS_END_CODE_QUOTE="${BATS_CODE_QUOTE_STYLE:1:1}"
+  export BATS_BEGIN_CODE_QUOTE BATS_END_CODE_QUOTE
   ;;
-  custom)
-    if [[ ${BATS_BEGIN_CODE_QUOTE-BATS_BEGIN_CODE_QUOTE_UNSET} == BATS_BEGIN_CODE_QUOTE_UNSET 
-        || ${BATS_END_CODE_QUOTE-BATS_BEGIN_CODE_QUOTE_UNSET} == BATS_BEGIN_CODE_QUOTE_UNSET ]]; then
-      printf "ERROR: BATS_CODE_QUOTE_STYLE=custom requires BATS_BEGIN_CODE_QUOTE and BATS_END_CODE_QUOTE to be set\n" >&2
-      exit 1
-    fi
-  ;;
-  *)
-    printf "ERROR: Unknown BATS_CODE_QUOTE_STYLE: %s\n" "$BATS_CODE_QUOTE_STYLE" >&2
+custom)
+  if [[ ${BATS_BEGIN_CODE_QUOTE-BATS_BEGIN_CODE_QUOTE_UNSET} == BATS_BEGIN_CODE_QUOTE_UNSET ||
+    ${BATS_END_CODE_QUOTE-BATS_BEGIN_CODE_QUOTE_UNSET} == BATS_BEGIN_CODE_QUOTE_UNSET ]]; then
+    printf "ERROR: BATS_CODE_QUOTE_STYLE=custom requires BATS_BEGIN_CODE_QUOTE and BATS_END_CODE_QUOTE to be set\n" >&2
     exit 1
+  fi
+  ;;
+*)
+  printf "ERROR: Unknown BATS_CODE_QUOTE_STYLE: %s\n" "$BATS_CODE_QUOTE_STYLE" >&2
+  exit 1
   ;;
 esac
 
@@ -453,12 +456,12 @@ trap 'BATS_INTERRUPTED=true' INT # let the lower levels handle the interruption
 set -o pipefail execfail
 
 if [[ -n "$report_formatter" ]]; then
-  exec bats-exec-suite "${flags[@]}" "${filenames[@]}" | \
-    tee >("$interpolated_report_formatter" "${report_formatter_flags[@]}" >"${BATS_REPORT_OUTPUT_DIR}/${BATS_REPORT_FILENAME}") | \
-    bats_test_count_validator | \
+  exec bats-exec-suite "${flags[@]}" "${filenames[@]}" |
+    tee >("$interpolated_report_formatter" "${report_formatter_flags[@]}" >"${BATS_REPORT_OUTPUT_DIR}/${BATS_REPORT_FILENAME}") |
+    bats_test_count_validator |
     "$interpolated_formatter" "${formatter_flags[@]}"
 else
-  exec bats-exec-suite "${flags[@]}" "${filenames[@]}" | \
-    bats_test_count_validator | \
+  exec bats-exec-suite "${flags[@]}" "${filenames[@]}" |
+    bats_test_count_validator |
     "$interpolated_formatter" "${formatter_flags[@]}"
 fi
diff --git a/libexec/bats-core/bats-exec-file b/libexec/bats-core/bats-exec-file
--- a/libexec/bats-core/bats-exec-file
+++ b/libexec/bats-core/bats-exec-file
@@ -6,7 +6,7 @@ num_jobs=${BATS_NUMBER_OF_PARALLEL_JOBS:-1}
 extended_syntax=''
 BATS_TRACE_LEVEL="${BATS_TRACE_LEVEL:-0}"
 declare -r BATS_RETRY_RETURN_CODE=126
-export BATS_TEST_RETRIES=0 # no retries by default 
+export BATS_TEST_RETRIES=0 # no retries by default
 
 while [[ "$#" -ne 0 ]]; do
   case "$1" in
@@ -25,8 +25,8 @@ while [[ "$#" -ne 0 ]]; do
     # use singular to allow for users to override in file
     BATS_NO_PARALLELIZE_WITHIN_FILE=1
     ;;
-  --dummy-flag)
-    ;;
+  --dummy-flag) ;;
+
   --trace)
     flags+=('--trace')
     ;;
@@ -76,7 +76,7 @@ bats_run_setup_file() {
 
   # these are defined only to avoid errors when referencing undefined variables down the line
   # shellcheck disable=2034
-  BATS_TEST_NAME=      # used in tracing.bash
+  BATS_TEST_NAME= # used in tracing.bash
   # shellcheck disable=2034
   BATS_TEST_COMPLETED= # used in tracing.bash
 
@@ -92,7 +92,7 @@ bats_run_setup_file() {
   local status=0
   # get the setup_file/teardown_file functions for this file (if it has them)
   # shellcheck disable=SC1090
-  source "$BATS_TEST_SOURCE"  >>"$BATS_OUT" 2>&1
+  source "$BATS_TEST_SOURCE" >>"$BATS_OUT" 2>&1
 
   BATS_SOURCE_FILE_COMPLETED=1
 
@@ -109,7 +109,7 @@ bats_run_teardown_file() {
   # rely on bats_error_trap to catch failures
   teardown_file >>"$BATS_OUT" 2>&1 || bats_teardown_file_status=$?
 
-  if (( bats_teardown_file_status == 0 )); then
+  if ((bats_teardown_file_status == 0)); then
     BATS_TEARDOWN_FILE_COMPLETED=1
   elif [[ -n "${BATS_SETUP_FILE_COMPLETED:-}" ]]; then
     BATS_DEBUG_LAST_STACK_TRACE_IS_VALID=1
@@ -133,13 +133,13 @@ bats_file_exit_trap() {
   fi
   trap - ERR EXIT
   local failure_reason
-  local -i failure_test_index=$(( BATS_FILE_FIRST_TEST_NUMBER_IN_SUITE + 1 ))
+  local -i failure_test_index=$((BATS_FILE_FIRST_TEST_NUMBER_IN_SUITE + 1))
   if [[ -z "$BATS_SETUP_FILE_COMPLETED" || -z "$BATS_TEARDOWN_FILE_COMPLETED" ]]; then
     if [[ -z "$BATS_SETUP_FILE_COMPLETED" ]]; then
       failure_reason='setup_file'
     elif [[ -z "$BATS_TEARDOWN_FILE_COMPLETED" ]]; then
       failure_reason='teardown_file'
-      failure_test_index=$(( BATS_FILE_FIRST_TEST_NUMBER_IN_SUITE + ${#tests_to_run[@]} + 1 ))
+      failure_test_index=$((BATS_FILE_FIRST_TEST_NUMBER_IN_SUITE + ${#tests_to_run[@]} + 1))
     elif [[ -z "$BATS_SOURCE_FILE_COMPLETED" ]]; then
       failure_reason='source'
     else
@@ -150,7 +150,7 @@ bats_file_exit_trap() {
     bats_get_failure_stack_trace stack_trace
     bats_print_stack_trace "${stack_trace[@]}" >&3
     bats_print_failed_command "${stack_trace[@]}" >&3
-    bats_prefix_lines_for_tap_output < "$BATS_OUT" | bats_replace_filename >&3
+    bats_prefix_lines_for_tap_output <"$BATS_OUT" | bats_replace_filename >&3
     rm -rf "$BATS_OUT"
     bats_exec_file_status=1
   fi
@@ -183,7 +183,7 @@ bats_forward_output_of_parallel_test() {
 bats_is_next_parallel_test_finished() {
   local PID
   # get the pid of the next potentially finished test
-  PID=$(cat "$output_folder/$(( test_number_in_suite_of_last_finished_test + 1 ))/pid")
+  PID=$(cat "$output_folder/$((test_number_in_suite_of_last_finished_test + 1))/pid")
   # try to send a signal to this process
   # if it fails, the process exited,
   # if it succeeds, the process is still running
@@ -198,10 +198,10 @@ bats_is_next_parallel_test_finished() {
 bats_forward_output_for_parallel_tests() {
   local status=0
   # was the next test already started?
-  while (( test_number_in_suite_of_last_finished_test + 1 <= test_number_in_suite )); do
+  while ((test_number_in_suite_of_last_finished_test + 1 <= test_number_in_suite)); do
     # if we are okay with waiting or if the test has already been finished
-    if [[ "$1" == "blocking" ]] || bats_is_next_parallel_test_finished ; then
-      (( ++test_number_in_suite_of_last_finished_test ))
+    if [[ "$1" == "blocking" ]] || bats_is_next_parallel_test_finished; then
+      ((++test_number_in_suite_of_last_finished_test))
       bats_forward_output_of_parallel_test "$test_number_in_suite_of_last_finished_test" || status=$?
     else
       # non-blocking and the process has not finished -> abort the printing
@@ -214,7 +214,7 @@ bats_forward_output_for_parallel_tests() {
 bats_run_test_with_retries() { # <args>
   local status=0
   local should_try_again=1 try_number
-  for ((try_number=1; should_try_again; ++try_number)); do
+  for ((try_number = 1; should_try_again; ++try_number)); do
     if "$BATS_LIBEXEC/bats-exec-test" "$@" "$try_number"; then
       should_try_again=0
     else
@@ -247,8 +247,8 @@ bats_run_tests_in_parallel() {
       ((++test_number_in_file))
       mkdir -p "$output_folder/$test_number_in_suite"
       bats_semaphore_run "$output_folder/$test_number_in_suite" \
-                          bats_run_test_with_retries "${flags[@]}" "$filename" "$test_name" "$test_number_in_suite" "$test_number_in_file" \
-                          > "$output_folder/$test_number_in_suite/pid"
+        bats_run_test_with_retries "${flags[@]}" "$filename" "$test_name" "$test_number_in_suite" "$test_number_in_file" \
+        >"$output_folder/$test_number_in_suite/pid"
     fi
     # print results early to get interactive feedback
     bats_forward_output_for_parallel_tests non-blocking || status=1 # ignore if we did not finish yet
@@ -268,7 +268,7 @@ bats_read_tests_list_file() {
     # use simple string operations to work around that issue
     if [[ "$filename" == "${test_line::${#filename}}" ]]; then
       # get the rest of the line without the separator \t
-      test_name=${test_line:$((1 + ${#filename} ))}
+      test_name=${test_line:$((1 + ${#filename}))}
       tests_to_run+=("$test_name")
       # save the first test's number for later iteration
       # this assumes that tests for a file are stored consecutive in the file!
@@ -290,7 +290,7 @@ bats_run_tests() {
     bats_run_tests_in_parallel "$BATS_RUN_TMPDIR/parallel_output" || bats_exec_file_status=1
   else
     local test_number_in_suite=$BATS_FILE_FIRST_TEST_NUMBER_IN_SUITE \
-          test_number_in_file=0
+      test_number_in_file=0
     for test_name in "${tests_to_run[@]}"; do
       if [[ "${BATS_INTERRUPTED-NOTSET}" != NOTSET ]]; then
         bats_exec_file_status=130 # bash's code for SIGINT exits
@@ -301,7 +301,7 @@ bats_run_tests() {
         ((++test_number_in_suite))
         ((++test_number_in_file))
         bats_run_test_with_retries "${flags[@]}" "$filename" "$test_name" \
-                                    "$test_number_in_suite" "$test_number_in_file" || bats_exec_file_status=$?
+          "$test_number_in_suite" "$test_number_in_file" || bats_exec_file_status=$?
       fi
     done
   fi
diff --git a/libexec/bats-core/bats-exec-test b/libexec/bats-core/bats-exec-test
--- a/libexec/bats-core/bats-exec-test
+++ b/libexec/bats-core/bats-exec-test
@@ -20,10 +20,10 @@ while [[ "$#" -ne 0 ]]; do
     # shellcheck disable=SC2034
     BATS_EXTENDED_SYNTAX='-x'
     ;;
-  --dummy-flag)
-    ;;
+  --dummy-flag) ;;
+
   --trace)
-    (( ++BATS_TRACE_LEVEL )) # avoid returning 0
+    ((++BATS_TRACE_LEVEL)) # avoid returning 0
     ;;
   --print-output-on-failure)
     BATS_PRINT_OUTPUT_ON_FAILURE=1
@@ -72,7 +72,7 @@ bats_create_test_tmpdirs() {
     exit 1
   fi
 
-  printf "%s\n" "$BATS_TEST_NAME" > "$BATS_TEST_TMPDIR.name"
+  printf "%s\n" "$BATS_TEST_NAME" >"$BATS_TEST_TMPDIR.name"
 
   export BATS_TEST_TMPDIR
 }
@@ -91,7 +91,7 @@ bats_teardown_trap() {
   # The second parameter is optional and corresponds for to the killer pid
   # that will be forwarded to the exit trap to kill it if necesary
   local killer_pid=${2:-}
-  
+
   # mark the start of this function to distinguish where skip is called
   # parameter 1 will signify the reason why this function was called
   # this is used to identify when this is called as exit trap function
@@ -124,15 +124,15 @@ bats_exit_trap() {
   if [[ -n "$BATS_TEST_SKIPPED" ]]; then
     exit_metadata=' # skip'
     if [[ "$BATS_TEST_SKIPPED" != '1' ]]; then
-        exit_metadata+=" $BATS_TEST_SKIPPED"
+      exit_metadata+=" $BATS_TEST_SKIPPED"
     fi
   elif [[ "${BATS_TIMED_OUT-NOTSET}" != NOTSET ]]; then
-     exit_metadata=" # timeout after ${BATS_TEST_TIMEOUT}s"
+    exit_metadata=" # timeout after ${BATS_TEST_TIMEOUT}s"
   fi
 
   BATS_TEST_TIME=''
   if [[ -n "$BATS_ENABLE_TIMING" ]]; then
-    BATS_TEST_TIME=" in "$(( $(get_mills_since_epoch) - BATS_TEST_START_TIME ))"ms"
+    BATS_TEST_TIME=" in "$(($(get_mills_since_epoch) - BATS_TEST_START_TIME))"ms"
   fi
 
   local print_bats_out="${BATS_SHOW_OUTPUT_OF_SUCCEEDING_TESTS}"
@@ -153,7 +153,7 @@ bats_exit_trap() {
     fi
     if bats_should_retry_test; then
       should_retry=1
-      status=126 # signify retry
+      status=126                # signify retry
       rm -r "$BATS_TEST_TMPDIR" # clean up for retry
     else
       printf 'not ok %d %s%s\n' "$BATS_SUITE_TEST_NUMBER" "${BATS_TEST_NAME_PREFIX:-}${BATS_TEST_DESCRIPTION}${BATS_TEST_TIME}" "$exit_metadata" >&3
@@ -169,9 +169,9 @@ bats_exit_trap() {
         if [[ -n "${stderr:-}" ]]; then
           printf "Last stderr: \n%s\n" "$stderr"
         fi
-      fi  >> "$BATS_OUT"
+      fi >>"$BATS_OUT"
 
-      print_bats_out=1    
+      print_bats_out=1
       status=1
       local state=failed
     fi
@@ -183,10 +183,10 @@ bats_exit_trap() {
   fi
 
   if [[ -z "$should_retry" ]]; then
-    printf "%s %s\t%s\n" "$state" "$BATS_TEST_FILENAME" "$BATS_TEST_NAME" >> "$BATS_RUNLOG_FILE"
+    printf "%s %s\t%s\n" "$state" "$BATS_TEST_FILENAME" "$BATS_TEST_NAME" >>"$BATS_RUNLOG_FILE"
 
     if [[ $print_bats_out ]]; then
-      bats_prefix_lines_for_tap_output < "$BATS_OUT" | bats_replace_filename >&3
+      bats_prefix_lines_for_tap_output <"$BATS_OUT" | bats_replace_filename >&3
     fi
   fi
   if [[ $BATS_GATHER_TEST_OUTPUTS_IN ]]; then
@@ -201,7 +201,7 @@ bats_exit_trap() {
 }
 
 # Marks the test as failed due to timeout.
-# The actual termination of subprocesses is done via pkill in the background 
+# The actual termination of subprocesses is done via pkill in the background
 # process in bats_start_timeout_countdown
 bats_timeout_trap() {
   BATS_TIMED_OUT=1
@@ -210,24 +210,24 @@ bats_timeout_trap() {
 }
 
 bats_get_child_processes_of() { # <parent-pid>
-    local -ri parent_pid=${1?}
-    {
-      read -ra header
-      local pid_col ppid_col
-      for (( i = 0; i < ${#header[@]}; ++i )); do
-        if [[ ${header[$i]} == "PID" ]]; then
-          pid_col=$i
-        fi
-        if [[ ${header[$i]} == "PPID" ]]; then
-          ppid_col=$i
-        fi
-      done
-      while read -ra row; do
-        if (( ${row[$ppid_col]} == parent_pid )); then
-          printf "%d\n" "${row[$pid_col]}"
-        fi
-      done
-    } < <(ps -ef "$parent_pid")
+  local -ri parent_pid=${1?}
+  {
+    read -ra header
+    local pid_col ppid_col
+    for ((i = 0; i < ${#header[@]}; ++i)); do
+      if [[ ${header[$i]} == "PID" ]]; then
+        pid_col=$i
+      fi
+      if [[ ${header[$i]} == "PPID" ]]; then
+        ppid_col=$i
+      fi
+    done
+    while read -ra row; do
+      if ((${row[$ppid_col]} == parent_pid)); then
+        printf "%d\n" "${row[$pid_col]}"
+      fi
+    done
+  } < <(ps -ef "$parent_pid")
 }
 
 bats_kill_childprocesses_of() { # <parent-pid>
@@ -248,7 +248,7 @@ bats_kill_childprocesses_of() { # <parent-pid>
 # Ruled out:
 # USR1/2 - not available on Windows
 # SIGALRM - interferes with sleep:
-#           "sleep(3) may be implemented using SIGALRM; mixing calls to alarm() 
+#           "sleep(3) may be implemented using SIGALRM; mixing calls to alarm()
 #           and sleep(3) is a bad idea." ~ https://linux.die.net/man/2/alarm
 bats_start_timeout_countdown() { # <timeout>
   local -ri timeout=$1
@@ -261,16 +261,16 @@ bats_start_timeout_countdown() { # <timeout>
   fi
   # Start another process to kill the children of this process
   (
-     sleep "$timeout" &
-     # sleep won't recieve signals, so we use wait below
-     # and kill sleep explicitly when signalled to do so
-     # shellcheck disable=SC2064
-     trap "kill $!; exit 0" ABRT
-     wait
-     if kill -ABRT "$target_pid"; then
-        # get rid of signal blocking child processes (like sleep)
-        bats_kill_childprocesses_of "$target_pid"
-     fi  &> /dev/null
+    sleep "$timeout" &
+    # sleep won't recieve signals, so we use wait below
+    # and kill sleep explicitly when signalled to do so
+    # shellcheck disable=SC2064
+    trap "kill $!; exit 0" ABRT
+    wait
+    if kill -ABRT "$target_pid"; then
+      # get rid of signal blocking child processes (like sleep)
+      bats_kill_childprocesses_of "$target_pid"
+    fi &>/dev/null
   ) &
 }
 
@@ -283,9 +283,9 @@ get_mills_since_epoch() {
   local ms_since_epoch
   ms_since_epoch=$(date +%s%N)
   if [[ "$ms_since_epoch" == *N || "${#ms_since_epoch}" -lt 19 ]]; then
-        ms_since_epoch=$(( $(date +%s) * 1000 ))
+    ms_since_epoch=$(($(date +%s) * 1000))
   else
-        ms_since_epoch=$(( ms_since_epoch / 1000000 ))
+    ms_since_epoch=$((ms_since_epoch / 1000000))
   fi
 
   printf "%d\n" "$ms_since_epoch"
