Fix infinite wait when invoking "bats -j5" instead of "bats -j 5"
bats's option parser translates "-j5" to "-j -5". This caused a negative
number of "slots" (threads) to be available and the test to silently
hang forever. Not nice.

Add a $num_jobs sanity check to fail immediately like this:

```
Invalid number of jobs: -5
tests.bats
   bats warning: Executed 0 instead of expected 3 tests

3 tests, 0 failures, 3 not run
```

Non-numeric arguments (e.g.: -jf) evaluate to zero which also fails the
check.

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

diff --git a/libexec/bats-core/bats-exec-file b/libexec/bats-core/bats-exec-file
--- a/libexec/bats-core/bats-exec-file
+++ b/libexec/bats-core/bats-exec-file
@@ -285,6 +285,11 @@ bats_read_tests_list_file() {
 bats_run_tests() {
   bats_exec_file_status=0
 
+  if [[ "$num_jobs" -lt 1 ]]; then
+    printf 'Invalid number of jobs: %s\n' "$num_jobs" >&2
+    exit 1
+  fi
+
   if [[ "$num_jobs" != 1 && "${BATS_NO_PARALLELIZE_WITHIN_FILE-False}" == False ]]; then
     export BATS_SEMAPHORE_NUMBER_OF_SLOTS="$num_jobs"
     bats_run_tests_in_parallel "$BATS_RUN_TMPDIR/parallel_output" || bats_exec_file_status=1
