Shorten tmpdirs for restricted systems
use flat structure which also gives empty dirs.

diff --git a/libexec/bats-core/bats b/libexec/bats-core/bats
--- a/libexec/bats-core/bats
+++ b/libexec/bats-core/bats
@@ -239,13 +239,15 @@ if [[ -n "${BATS_RUN_TMPDIR:-}" ]];then
     printf "Error: Failed to create BATS_RUN_TMPDIR (%s)\n" "$BATS_RUN_TMPDIR" >&2
     exit 1
   fi
-elif ! BATS_RUN_TMPDIR=$(mktemp -d "${BATS_TMPDIR}/bats-run-$BATS_ROOT_PID-XXXXXX");then
-  printf "Error: Failed to create BATS_RUN_TMPDIR (%s) with mktemp\n" "${BATS_TMPDIR}/bats-run-$BATS_ROOT_PID-XXXXXX" >&2
+elif ! BATS_RUN_TMPDIR=$(mktemp -d "${BATS_TMPDIR}/bats-run-XXXXXX");then
+  printf "Error: Failed to create BATS_RUN_TMPDIR (%s) with mktemp\n" "${BATS_TMPDIR}/bats-run-XXXXXX" >&2
   exit 1
 fi
 
 if [[ -n "$BATS_TEMPDIR_CLEANUP" ]]; then
   trap 'rm -rf "$BATS_RUN_TMPDIR"' ERR EXIT
+else
+  trap 'printf "BATS_RUN_TMPDIR: $BATS_RUN_TMPDIR\n">&2' EXIT
 fi
 
 if [[ "$formatter" != "tap" ]]; then
diff --git a/libexec/bats-core/bats-exec-file b/libexec/bats-core/bats-exec-file
--- a/libexec/bats-core/bats-exec-file
+++ b/libexec/bats-core/bats-exec-file
@@ -64,13 +64,7 @@ if [[ ! -f "$filename" ]]; then
   exit 1
 fi
 
-BATS_TEST_FILENAME="$filename"
-
-if ! BATS_FILE_TMPDIR=$(mktemp -d "${BATS_SUITE_TMPDIR}/file-tmpdir-$(basename "${BATS_TEST_FILENAME}")-XXXXXX");then
-  printf '%s\n' "Failed to create BATS_FILE_TMPDIR with mktemp" >&2
-  exit 1
-fi
-export BATS_FILE_TMPDIR
+export BATS_TEST_FILENAME="$filename"
 
 # shellcheck source=lib/bats-core/preprocessing.bash
 # shellcheck disable=SC2153
@@ -298,6 +292,23 @@ bats_run_tests() {
   export status
 }
 
+bats_create_file_tempdirs() {
+  local bats_files_tmpdir="${BATS_RUN_TMPDIR}/file"
+  if [[ ! -d $bats_files_tmpdir ]]; then
+    if ! mkdir "$bats_files_tmpdir"; then
+      printf 'Failed to create %s\n' "$bats_files_tmpdir" >&2
+      exit 1
+    fi
+  fi
+  BATS_FILE_TMPDIR="$bats_files_tmpdir/$first_test_number_in_suite"
+  if ! mkdir "$BATS_FILE_TMPDIR"; then
+    printf 'Failed to create %s\n' "$BATS_FILE_TMPDIR" >&2
+    exit 1
+  fi
+  ln -s "$BATS_TEST_FILENAME" "$BATS_FILE_TMPDIR-$(basename "$BATS_TEST_FILENAME").source_file"
+  export BATS_FILE_TMPDIR
+}
+
 trap 'BATS_INTERRUPTED=true' INT
 
 if [[ -n "$extended_syntax" ]]; then
@@ -305,6 +316,8 @@ if [[ -n "$extended_syntax" ]]; then
 fi
 
 bats_read_tests_list_file
+bats_create_file_tempdirs
+
 # don't run potentially expensive setup/teardown_file
 # when there are no tests to run
 if [[ ${#tests_to_run[@]} -eq 0 ]]; then
diff --git a/libexec/bats-core/bats-exec-suite b/libexec/bats-core/bats-exec-suite
--- a/libexec/bats-core/bats-exec-suite
+++ b/libexec/bats-core/bats-exec-suite
@@ -146,11 +146,11 @@ if [[ "${test_count}" == 0 ]]; then
   exit
 fi
 
-if ! BATS_SUITE_TMPDIR=$(mktemp -d "${BATS_RUN_TMPDIR}/suite-tmpdir-XXXXXX");then
-  printf '%s\n' "Failed to create BATS_SUITE_TMPDIR with mktemp" >&2
+export BATS_SUITE_TMPDIR="${BATS_RUN_TMPDIR}/suite"
+if ! mkdir "$BATS_SUITE_TMPDIR"; then
+  printf '%s\n' "Failed to create BATS_SUITE_TMPDIR" >&2
   exit 1
 fi
-export BATS_SUITE_TMPDIR
 
 # Deduplicate filenames (without reordering) to avoid running duplicate tests n by n times.
 # (see https://github.com/bats-core/bats-core/issues/329)
diff --git a/libexec/bats-core/bats-exec-test b/libexec/bats-core/bats-exec-test
--- a/libexec/bats-core/bats-exec-test
+++ b/libexec/bats-core/bats-exec-test
@@ -66,11 +66,25 @@ elif [[ ! -f "$BATS_TEST_FILENAME" ]]; then
   exit 1
 fi
 
-if ! BATS_TEST_TMPDIR=$(mktemp -d "${BATS_FILE_TMPDIR}/test-tmpdir-${BATS_TEST_NAME::200}-XXXXXX");then
-  printf '%s\n' "Failed to create BATS_TEST_TMPDIR with mktemp" >&2
-  exit 1
-fi
-export BATS_TEST_TMPDIR
+bats_create_test_tmpdirs() {
+  local tests_tmpdir="${BATS_RUN_TMPDIR}/test/"
+  if [[ ! -d $tests_tmpdir ]]; then
+    if ! mkdir "$tests_tmpdir"; then
+      printf 'Failed to create: %s\n' "$tests_tmpdir" >&2
+      exit 1
+    fi
+  fi
+
+  BATS_TEST_TMPDIR="$tests_tmpdir/$BATS_SUITE_TEST_NUMBER"
+  if ! mkdir "$BATS_TEST_TMPDIR"; then
+    printf 'Failed to create BATS_TEST_TMPDIR: %s\n' "$BATS_TEST_TMPDIR" >&2
+    exit 1
+  fi
+
+  printf "%s\n" "$BATS_TEST_NAME" > "$BATS_TEST_TMPDIR.name"
+
+  export BATS_TEST_TMPDIR
+}
 
 # load the test helper functions like `load` or `run` that are needed to run a (preprocessed) .bats file without bash errors
 # shellcheck source=lib/bats-core/test_functions.bash disable=SC2153
@@ -229,6 +243,7 @@ source "$BATS_ROOT/lib/bats-core/preprocessing.bash"
 
 exec 3<&1
 
+bats_create_test_tmpdirs
 # Run the given test.
 bats_evaluate_preprocessed_source
 bats_perform_test
