Run through shfmt

diff --git a/libexec/bats-core/bats b/libexec/bats-core/bats
--- a/libexec/bats-core/bats
+++ b/libexec/bats-core/bats
@@ -4,22 +4,22 @@ set -e
 export BATS_VERSION='1.2.0-dev'
 
 version() {
-  printf 'Bats %s\n' "$BATS_VERSION"
+	printf 'Bats %s\n' "$BATS_VERSION"
 }
 
 abort() {
-  printf 'Error: %s\n' "$1" >&2
-  usage >&2
-  exit 1
+	printf 'Error: %s\n' "$1" >&2
+	usage >&2
+	exit 1
 }
 
 usage() {
-  local cmd="${0##*/}"
-  local line
+	local cmd="${0##*/}"
+	local line
 
-  while IFS= read -r line; do
-    printf '%s\n' "$line"
-  done <<END_OF_HELP_TEXT
+	while IFS= read -r line; do
+		printf '%s\n' "$line"
+	done <<END_OF_HELP_TEXT
 Usage: $cmd [-cr] [-f <regex>] [-j <jobs>] [-p | -t] <test>...
        $cmd [-h | -v]
 
@@ -44,23 +44,23 @@ END_OF_HELP_TEXT
 }
 
 expand_link() {
-  readlink="$(type -p greadlink readlink | head -1)"
-  "$readlink" -f "$1"
+	readlink="$(type -p greadlink readlink | head -1)"
+	"$readlink" -f "$1"
 }
 
 expand_path() {
-  local path="${1%/}"
-  local dirname="${path%/*}"
-  local result="$2"
+	local path="${1%/}"
+	local dirname="${path%/*}"
+	local result="$2"
 
-  if [[ "$dirname" == "$path" ]]; then
-    dirname="$PWD"
-  else
-    cd "$dirname"
-    dirname="$PWD"
-    cd "$OLDPWD"
-  fi
-  printf -v "$result" '%s/%s' "$dirname" "${path##*/}"
+	if [[ "$dirname" == "$path" ]]; then
+		dirname="$PWD"
+	else
+		cd "$dirname"
+		dirname="$PWD"
+		cd "$OLDPWD"
+	fi
+	printf -v "$result" '%s/%s' "$dirname" "${path##*/}"
 }
 
 BATS_LIBEXEC="$(dirname "$(expand_link "${BASH_SOURCE[0]}")")"
@@ -73,18 +73,18 @@ arguments=()
 
 # Unpack single-character options bundled together, e.g. -cr, -pr.
 for arg in "$@"; do
-  if [[ "$arg" =~ ^-[^-]. ]]; then
-    index=1
-    while option="${arg:$((index++)):1}"; do
-      if [[ -z "$option" ]]; then
-        break
-      fi
-      arguments+=("-$option")
-    done
-  else
-    arguments+=("$arg")
-  fi
-  shift
+	if [[ "$arg" =~ ^-[^-]. ]]; then
+		index=1
+		while option="${arg:$((index++)):1}"; do
+			if [[ -z "$option" ]]; then
+				break
+			fi
+			arguments+=("-$option")
+		done
+	else
+		arguments+=("$arg")
+	fi
+	shift
 done
 
 set -- "${arguments[@]}"
@@ -97,94 +97,94 @@ formatter='tap'
 recursive=
 output=
 if [[ -z "${CI:-}" && -t 0 && -t 1 ]] && command -v tput >/dev/null; then
-  formatter='pretty'
+	formatter='pretty'
 fi
 
 while [[ "$#" -ne 0 ]]; do
-  case "$1" in
-  -h|--help)
-    version
-    usage
-    exit 0
-    ;;
-  -v|--version)
-    version
-    exit 0
-    ;;
-  -c|--count)
-    flags+=('-c')
-    ;;
-  -f|--filter)
-    shift
-    flags+=('-f' "$1")
-    ;;
-  -F|--formatter)
-    shift
-    if [[ $1 =~ ^(pretty|junit|tap)$ ]]; then
-      formatter="$1"
-    else
-      printf "Unknown formatter '%s', valid options are pretty, junit, tap\n" "$1"
-      exit 1
-    fi
-    ;;
-  -o|--output)
-    shift
-    output="$1"
-    ;;
-  -p|--pretty)
-    formatter='pretty'
-    ;;
-  -j|--jobs)
-    shift
-    flags+=('-j' "$1")
-    ;;
-  -r|--recursive)
-    recursive=1
-    ;;
-  -t|--tap)
-    formatter='tap'
-    ;;
-  -T|--timing)
-    flags+=('-T')
-    formatter_flags+=('-T')
-    ;;
-  -*)
-    abort "Bad command line option '$1'"
-    ;;
-  *)
-    arguments+=("$1")
-    ;;
-  esac
-  shift
+	case "$1" in
+	-h | --help)
+		version
+		usage
+		exit 0
+		;;
+	-v | --version)
+		version
+		exit 0
+		;;
+	-c | --count)
+		flags+=('-c')
+		;;
+	-f | --filter)
+		shift
+		flags+=('-f' "$1")
+		;;
+	-F | --formatter)
+		shift
+		if [[ $1 =~ ^(pretty|junit|tap)$ ]]; then
+			formatter="$1"
+		else
+			printf "Unknown formatter '%s', valid options are pretty, junit, tap\n" "$1"
+			exit 1
+		fi
+		;;
+	-o | --output)
+		shift
+		output="$1"
+		;;
+	-p | --pretty)
+		formatter='pretty'
+		;;
+	-j | --jobs)
+		shift
+		flags+=('-j' "$1")
+		;;
+	-r | --recursive)
+		recursive=1
+		;;
+	-t | --tap)
+		formatter='tap'
+		;;
+	-T | --timing)
+		flags+=('-T')
+		formatter_flags+=('-T')
+		;;
+	-*)
+		abort "Bad command line option '$1'"
+		;;
+	*)
+		arguments+=("$1")
+		;;
+	esac
+	shift
 done
 
 if [[ "$formatter" != "tap" ]]; then
-  flags+=('-x')
+	flags+=('-x')
 fi
 
 if [[ "${#arguments[@]}" -eq 0 ]]; then
-  abort 'Must specify at least one <test>'
+	abort 'Must specify at least one <test>'
 fi
 
 filenames=()
 for filename in "${arguments[@]}"; do
-  expand_path "$filename" 'filename'
+	expand_path "$filename" 'filename'
 
-  if [[ -d "$filename" ]]; then
-    shopt -s nullglob
-    if [[ "$recursive" -eq 1 ]]; then
-      while IFS= read -r -d $'\0' file; do
-        filenames+=("$file")
-      done < <(find "$filename" -type f -name '*.bats' -print0 | sort -z)
-    else
-      for suite_filename in "$filename"/*.bats; do
-        filenames+=("$suite_filename")
-      done
-    fi
-    shopt -u nullglob
-  else
-    filenames+=("$filename")
-  fi
+	if [[ -d "$filename" ]]; then
+		shopt -s nullglob
+		if [[ "$recursive" -eq 1 ]]; then
+			while IFS= read -r -d $'\0' file; do
+				filenames+=("$file")
+			done < <(find "$filename" -type f -name '*.bats' -print0 | sort -z)
+		else
+			for suite_filename in "$filename"/*.bats; do
+				filenames+=("$suite_filename")
+			done
+		fi
+		shopt -u nullglob
+	else
+		filenames+=("$filename")
+	fi
 done
 
 set -o pipefail execfail
diff --git a/libexec/bats-core/bats-exec-file b/libexec/bats-core/bats-exec-file
--- a/libexec/bats-core/bats-exec-file
+++ b/libexec/bats-core/bats-exec-file
@@ -6,29 +6,29 @@ num_jobs=1
 filter=''
 
 while [[ "$#" -ne 0 ]]; do
-  case "$1" in
-  -c)
-    ;;
-  -f)
-    shift
-    filter="$1"
-    flags+=('-f' "$filter")
-    ;;
-  -j)
-    shift
-    num_jobs="$1"
-    ;;
-  -T)
-    flags+=('-T')
-    ;;
-  -x)
-    flags+=('-x')
-    ;;
-  *)
-    break
-    ;;
-  esac
-  shift
+	case "$1" in
+	-c) ;;
+
+	-f)
+		shift
+		filter="$1"
+		flags+=('-f' "$filter")
+		;;
+	-j)
+		shift
+		num_jobs="$1"
+		;;
+	-T)
+		flags+=('-T')
+		;;
+	-x)
+		flags+=('-x')
+		;;
+	*)
+		break
+		;;
+	esac
+	shift
 done
 
 filename=$1
@@ -36,8 +36,8 @@ test_number=$2
 TESTS_FILE="$3"
 
 if [[ ! -f "$filename" ]]; then
-    printf 'Testfile "%s" not found\n' "$filename" >&2
-    exit 1
+	printf 'Testfile "%s" not found\n' "$filename" >&2
+	exit 1
 fi
 
 BATS_TEST_FILENAME="$filename"
@@ -47,115 +47,115 @@ BATS_TEST_FILENAME="$filename"
 source "$BATS_ROOT/lib/bats-core/preprocessing.bash"
 
 bats_run_setup_file() {
-  # shellcheck source=lib/bats-core/tracing.bash
-  # shellcheck disable=SC2153
-  source "$BATS_ROOT/lib/bats-core/tracing.bash"
-  # shellcheck source=lib/bats-core/test_functions.bash
-  # shellcheck disable=SC2153
-  source "$BATS_ROOT/lib/bats-core/test_functions.bash"
+	# shellcheck source=lib/bats-core/tracing.bash
+	# shellcheck disable=SC2153
+	source "$BATS_ROOT/lib/bats-core/tracing.bash"
+	# shellcheck source=lib/bats-core/test_functions.bash
+	# shellcheck disable=SC2153
+	source "$BATS_ROOT/lib/bats-core/test_functions.bash"
 
-  exec 3<&1
+	exec 3<&1
 
-  BATS_STACK_TRACE=()
-  BATS_CURRENT_STACK_TRACE=()
+	BATS_STACK_TRACE=()
+	BATS_CURRENT_STACK_TRACE=()
 
-  # these are defined only to avoid errors when referencing undefined variables down the line
-  BATS_TEST_NAME=
-  BATS_TEST_COMPLETED=
+	# these are defined only to avoid errors when referencing undefined variables down the line
+	BATS_TEST_NAME=
+	BATS_TEST_COMPLETED=
 
-  BATS_SETUP_FILE_COMPLETED=
-  BATS_TEARDOWN_FILE_COMPLETED=
-  BATS_ERROR_STATUS=
-  trap 'bats_debug_trap "$BASH_SOURCE"' DEBUG
-  trap 'bats_error_trap' ERR
-  trap 'bats_file_teardown_trap' EXIT
+	BATS_SETUP_FILE_COMPLETED=
+	BATS_TEARDOWN_FILE_COMPLETED=
+	BATS_ERROR_STATUS=
+	trap 'bats_debug_trap "$BASH_SOURCE"' DEBUG
+	trap 'bats_error_trap' ERR
+	trap 'bats_file_teardown_trap' EXIT
 
-  touch "$BATS_OUT"
-  # get the setup_file/teardown_file functions for this file (if it has them)
-  # shellcheck disable=SC1090
-  source "$BATS_TEST_SOURCE"
-  setup_file >>"$BATS_OUT" 2>&1
+	touch "$BATS_OUT"
+	# get the setup_file/teardown_file functions for this file (if it has them)
+	# shellcheck disable=SC1090
+	source "$BATS_TEST_SOURCE"
+	setup_file >>"$BATS_OUT" 2>&1
 
-  BATS_SETUP_FILE_COMPLETED=1
+	BATS_SETUP_FILE_COMPLETED=1
 }
 
 bats_run_teardown_file() {
-  # avoid running the therdown trap due to errors in teardown_file
-  trap 'bats_file_exit_trap' EXIT
-  local status=0
-  # rely on bats_error_trap to catch failures
-  teardown_file >>"$BATS_OUT" 2>&1 
+	# avoid running the therdown trap due to errors in teardown_file
+	trap 'bats_file_exit_trap' EXIT
+	local status=0
+	# rely on bats_error_trap to catch failures
+	teardown_file >>"$BATS_OUT" 2>&1
 
-  BATS_TEARDOWN_FILE_COMPLETED=1
+	BATS_TEARDOWN_FILE_COMPLETED=1
 }
 
 bats_file_teardown_trap() {
-  bats_error_trap
-  local status=0
-  bats_run_teardown_file
+	bats_error_trap
+	local status=0
+	bats_run_teardown_file
 
-  bats_file_exit_trap
+	bats_file_exit_trap
 }
 
 bats_file_exit_trap() {
-    trap - ERR EXIT
-    if [[ -z "$BATS_SETUP_FILE_COMPLETED" || -z "$BATS_TEARDOWN_FILE_COMPLETED" ]]; then
-      if [[ -z "$BATS_SETUP_FILE_COMPLETED" ]]; then
-        FAILURE_REASON='setup_file'
-      else 
-        FAILURE_REASON='teardown_file'
-      fi
-      printf "not ok %d %s\n" "$(( test_number + 1))" "$FAILURE_REASON failed" >&3
-      bats_print_stack_trace "${BATS_STACK_TRACE[@]}" >&3
-      bats_print_failed_command >&3
-      while IFS= read -r line; do
-          printf "# %s\n" "$line"
-      done < "$BATS_OUT" >&3
-      if [[ -n "$line" ]]; then
-        printf '# %s\n' "$line"
-      fi
-      rm -rf "$BATS_OUT"
-      status=1
-    fi
-    bats_cleanup_preprocessed_source
-    exit $status
+	trap - ERR EXIT
+	if [[ -z "$BATS_SETUP_FILE_COMPLETED" || -z "$BATS_TEARDOWN_FILE_COMPLETED" ]]; then
+		if [[ -z "$BATS_SETUP_FILE_COMPLETED" ]]; then
+			FAILURE_REASON='setup_file'
+		else
+			FAILURE_REASON='teardown_file'
+		fi
+		printf "not ok %d %s\n" "$((test_number + 1))" "$FAILURE_REASON failed" >&3
+		bats_print_stack_trace "${BATS_STACK_TRACE[@]}" >&3
+		bats_print_failed_command >&3
+		while IFS= read -r line; do
+			printf "# %s\n" "$line"
+		done <"$BATS_OUT" >&3
+		if [[ -n "$line" ]]; then
+			printf '# %s\n' "$line"
+		fi
+		rm -rf "$BATS_OUT"
+		status=1
+	fi
+	bats_cleanup_preprocessed_source
+	exit $status
 }
 
-function setup_file() { 
-    return 0 
+function setup_file() {
+	return 0
 }
 
-function teardown_file() { 
-    return 0 
+function teardown_file() {
+	return 0
 }
 
 bats_run_tests() {
-  status=0
-  tests_to_run=()
-  while read -r test_name; do
-    tests_to_run+=("$test_name")
-  done < "$TESTS_FILE"
+	status=0
+	tests_to_run=()
+	while read -r test_name; do
+		tests_to_run+=("$test_name")
+	done <"$TESTS_FILE"
 
-  if [[ "$num_jobs" != 1 ]]; then
-    # Only use GNU parallel when we want parallel execution -- there is a small
-    # amount of overhead using it over a simple loop in the serial case.
-    set -o pipefail
-    printf '%s\n' "${tests_to_run[@]}" | grep -v '^$' | \
-      parallel -qk -j "$num_jobs" --colsep="\t" -- bats-exec-test "${flags[@]}" "$filename" '{1}' "{=\$_=\$job->seq()+$test_number=}" || status=1
-  else
-    for test_name in "${tests_to_run[@]}"; do
-        # Only handle non-empty lines
-        if [[ $test_name ]]; then
-            ((++test_number))
-            if [[ "${#flags[@]}" -gt 0 ]]; then
-              bats-exec-test "${flags[@]}" "$filename" "$test_name" "$test_number" || status=1
-            else
-              bats-exec-test "$filename" "$test_name" "$test_number" || status=1
-            fi
-        fi
-    done
-  fi
-  export status
+	if [[ "$num_jobs" != 1 ]]; then
+		# Only use GNU parallel when we want parallel execution -- there is a small
+		# amount of overhead using it over a simple loop in the serial case.
+		set -o pipefail
+		printf '%s\n' "${tests_to_run[@]}" | grep -v '^$' |
+			parallel -qk -j "$num_jobs" --colsep="\t" -- bats-exec-test "${flags[@]}" "$filename" '{1}' "{=\$_=\$job->seq()+$test_number=}" || status=1
+	else
+		for test_name in "${tests_to_run[@]}"; do
+			# Only handle non-empty lines
+			if [[ $test_name ]]; then
+				((++test_number))
+				if [[ "${#flags[@]}" -gt 0 ]]; then
+					bats-exec-test "${flags[@]}" "$filename" "$test_name" "$test_number" || status=1
+				else
+					bats-exec-test "$filename" "$test_name" "$test_number" || status=1
+				fi
+			fi
+		done
+	fi
+	export status
 }
 
 # TODO: we want to run setup/teardown file but have following problems
@@ -163,12 +163,12 @@ bats_run_tests() {
 # 1.1 the preprocessing is defined in bats-exec-test so we don't have it here
 # 1.2 the load command is also defined in bats-exec-test
 # -> it is preferable to run this from bats-exec-test to avoid duplicating the preprocessing/helper commands
-# 2. we need the file setup to be run only once but its results (e.g. conditionally defined variables) 
+# 2. we need the file setup to be run only once but its results (e.g. conditionally defined variables)
 #    might need to be present in all tests of the file, not only the first
 # -> evaluate in suite, so that these results are inherited by the subshells
 # 3. prevent environment changes in sourced test files to leak over into other test files
 # -> each file gets its own context
-# 
+#
 # Running the preprocessing here (using shared code with bats-exec-test) requires us to do the clean up ourselves -> more traps
 
 bats_preprocess_source "$filename"
diff --git a/libexec/bats-core/bats-exec-suite b/libexec/bats-core/bats-exec-suite
--- a/libexec/bats-core/bats-exec-suite
+++ b/libexec/bats-core/bats-exec-suite
@@ -9,78 +9,78 @@ have_gnu_parallel=
 flags=()
 
 while [[ "$#" -ne 0 ]]; do
-  case "$1" in
-  -c)
-    count_only_flag=1
-    ;;
-  -f)
-    shift
-    filter="$1"
-    flags+=('-f' "$filter")
-    ;;
-  -j)
-    shift
-    num_jobs="$1"
-    flags+=('-j' "$num_jobs")
-    ;;
-  -T)
-    enable_timing=1
-    flags+=('-T')
-    ;;
-  -x)
-    flags+=('-x')
-    ;;
-  *)
-    break
-    ;;
-  esac
-  shift
+	case "$1" in
+	-c)
+		count_only_flag=1
+		;;
+	-f)
+		shift
+		filter="$1"
+		flags+=('-f' "$filter")
+		;;
+	-j)
+		shift
+		num_jobs="$1"
+		flags+=('-j' "$num_jobs")
+		;;
+	-T)
+		enable_timing=1
+		flags+=('-T')
+		;;
+	-x)
+		flags+=('-x')
+		;;
+	*)
+		break
+		;;
+	esac
+	shift
 done
 
-if ( type -p parallel &>/dev/null ); then
-  # shellcheck disable=SC2034
-  have_gnu_parallel=1
+if (type -p parallel &>/dev/null); then
+	# shellcheck disable=SC2034
+	have_gnu_parallel=1
 elif [[ "$num_jobs" != 1 ]]; then
-  printf 'bats: cannot execute "%s" jobs without GNU parallel\n' "$num_jobs" >&2
-  exit 1
+	printf 'bats: cannot execute "%s" jobs without GNU parallel\n' "$num_jobs" >&2
+	exit 1
 fi
 
 trap 'kill 0; exit 1' INT
 
 all_tests=()
 for filename in "$@"; do
-  if  [[ ! -f "$filename" ]]; then
-    printf 'bats: %s does not exist\n' "$filename" >&2
-    exit 1
-  fi
+	if [[ ! -f "$filename" ]]; then
+		printf 'bats: %s does not exist\n' "$filename" >&2
+		exit 1
+	fi
 
-  test_names=()
-  test_dupes=()
-  while read -r line; do
-    if [[ ! "$line" =~ ^bats_test_function\  ]]; then
-      continue
-    fi
-    line="${line%$'\r'}"
-    line="${line#* }"
-    all_tests+=( "$(printf "%s\t%s" "$filename" "$line")" )
-    if [[ " ${test_names[*]} " == *" $line "* ]]; then
-      test_dupes+=("$line")
-      continue
-    fi
-    test_names+=("$line")
-  done < <(BATS_TEST_FILTER="$filter" bats-preprocess "$filename")
+	test_names=()
+	test_dupes=()
+	while read -r line; do
+		if [[ ! "$line" =~ ^bats_test_function\  ]]; then
+			continue
+		fi
+		line="${line%$'\r'}"
+		line="${line#* }"
+		all_tests+=("$(printf "%s\t%s" "$filename" "$line")")
+		if [[ " ${test_names[*]} " == *" $line "* ]]; then
+			test_dupes+=("$line")
+			continue
+		fi
+		test_names+=("$line")
+	done < <(BATS_TEST_FILTER="$filter" bats-preprocess "$filename")
 
-  all_tests=("${all_tests[@]}" "${all_file_tests[@]}")
-  if [[ "${#test_dupes[@]}" -ne 0 ]]; then
-    printf 'bats warning: duplicate test name(s) in %s: %s\n' "$filename" "${test_dupes[*]}" >&2
-  fi
+	all_tests=("${all_tests[@]}" "${all_file_tests[@]}")
+	if [[ "${#test_dupes[@]}" -ne 0 ]]; then
+		printf 'bats warning: duplicate test name(s) in %s: %s\n' "$filename" "${test_dupes[*]}" >&2
+	fi
 done
 
 test_count="${#all_tests[@]}"
 
 if [[ -n "$count_only_flag" ]]; then
-  printf '%d\n' "${test_count}"
-  exit
+	printf '%d\n' "${test_count}"
+	exit
 fi
 
 status=0
@@ -88,28 +88,28 @@ printf '1..%d\n' "${test_count}"
 
 # No point on continuing if there's no tests.
 if [[ "${test_count}" == 0 ]]; then
-  exit
+	exit
 fi
 
 test_number=0
 for filename in "$@"; do
-  if [[ -n "$enable_timing" ]]; then
-    echo "suite $(basename "$filename")"
-  fi
-  TESTS_FILE=$(mktemp)
-  initial_test_number=$test_number
-  for test_line in "${all_tests[@]}"; do
-    if [[ "${test_line%%$'\t'*}" == "$filename" ]]; then
-      test_name="${test_line##*$'\t'}"
-      printf "%s"$'\n' "$test_name" >> "$TESTS_FILE"
-      (( ++test_number))
-    fi
-  done
-  bats-exec-file "${flags[@]}" "$filename" $initial_test_number "$TESTS_FILE" || status=1
-  rm "$TESTS_FILE"
+	if [[ -n "$enable_timing" ]]; then
+		echo "suite $(basename "$filename")"
+	fi
+	TESTS_FILE=$(mktemp)
+	initial_test_number=$test_number
+	for test_line in "${all_tests[@]}"; do
+		if [[ "${test_line%%$'\t'*}" == "$filename" ]]; then
+			test_name="${test_line##*$'\t'}"
+			printf "%s"$'\n' "$test_name" >>"$TESTS_FILE"
+			((++test_number))
+		fi
+	done
+	bats-exec-file "${flags[@]}" "$filename" $initial_test_number "$TESTS_FILE" || status=1
+	rm "$TESTS_FILE"
 done
 if [[ "${test_number}" != "${test_count}" ]]; then
-  printf '# bats warning: Only executed %s of %s tests\n' "$test_number" "$test_count"
-  status=1
+	printf '# bats warning: Only executed %s of %s tests\n' "$test_number" "$test_count"
+	status=1
 fi
 exit "$status"
