Avoid races when creating files/tests tmpdir

diff --git a/libexec/bats-core/bats-exec-file b/libexec/bats-core/bats-exec-file
--- a/libexec/bats-core/bats-exec-file
+++ b/libexec/bats-core/bats-exec-file
@@ -294,11 +294,9 @@ bats_run_tests() {
 
 bats_create_file_tempdirs() {
   local bats_files_tmpdir="${BATS_RUN_TMPDIR}/file"
-  if [[ ! -d $bats_files_tmpdir ]]; then
-    if ! mkdir "$bats_files_tmpdir"; then
-      printf 'Failed to create %s\n' "$bats_files_tmpdir" >&2
-      exit 1
-    fi
+  if ! mkdir -p "$bats_files_tmpdir"; then
+    printf 'Failed to create %s\n' "$bats_files_tmpdir" >&2
+    exit 1
   fi
   BATS_FILE_TMPDIR="$bats_files_tmpdir/$first_test_number_in_suite"
   if ! mkdir "$BATS_FILE_TMPDIR"; then
diff --git a/libexec/bats-core/bats-exec-test b/libexec/bats-core/bats-exec-test
--- a/libexec/bats-core/bats-exec-test
+++ b/libexec/bats-core/bats-exec-test
@@ -68,11 +68,9 @@ fi
 
 bats_create_test_tmpdirs() {
   local tests_tmpdir="${BATS_RUN_TMPDIR}/test/"
-  if [[ ! -d $tests_tmpdir ]]; then
-    if ! mkdir "$tests_tmpdir"; then
-      printf 'Failed to create: %s\n' "$tests_tmpdir" >&2
-      exit 1
-    fi
+  if ! mkdir -p "$tests_tmpdir"; then
+    printf 'Failed to create: %s\n' "$tests_tmpdir" >&2
+    exit 1
   fi
 
   BATS_TEST_TMPDIR="$tests_tmpdir/$BATS_SUITE_TEST_NUMBER"
