Implement dynamic test registration
- simplify stack trace limiting

diff --git a/libexec/bats-core/bats-exec-suite b/libexec/bats-core/bats-exec-suite
--- a/libexec/bats-core/bats-exec-suite
+++ b/libexec/bats-core/bats-exec-suite
@@ -8,7 +8,7 @@ parallel_binary_name=${BATS_PARALLEL_BINARY_NAME:-"parallel"}
 bats_no_parallelize_across_files=${BATS_NO_PARALLELIZE_ACROSS_FILES-}
 bats_no_parallelize_within_files=
 filter_status=''
-filter_tags_list=()
+gather_tests_flags=('--dummy-flag')
 flags=('--dummy-flag') # add a dummy flag to prevent unset variable errors on empty array expansion in old bash versions
 setup_suite_file=''
 BATS_TRACE_LEVEL="${BATS_TRACE_LEVEL:-0}"
@@ -59,16 +59,7 @@ while [[ "$#" -ne 0 ]]; do
     ;;
   --filter-tags)
     shift
-    IFS=, read -ra tags <<<"$1" || true
-    if ((${#tags[@]} > 0)); then
-      for ((i = 0; i < ${#tags[@]}; ++i)); do
-        bats_trim "tags[$i]" "${tags[$i]}"
-      done
-      bats_sort sorted_tags "${tags[@]}"
-      IFS=, filter_tags_list+=("${sorted_tags[*]}")
-    else
-      filter_tags_list+=("")
-    fi
+    gather_tests_flags+=("--filter-tags" "$1")
     ;;
   --dummy-flag) ;;
 
@@ -112,99 +103,10 @@ fi
 
 # create a file that contains all (filtered) tests to run from all files
 TESTS_LIST_FILE="${BATS_RUN_TMPDIR}/test_list_file.txt"
-focus_mode=
-bats_gather_tests() {
-  local line test_line tags
-  all_tests=()
-  for filename in "$@"; do
-    if [[ ! -f "$filename" ]]; then
-      abort "Test file \"${filename}\" does not exist"
-    fi
-
-    test_names=()
-    test_dupes=()
-    while read -r line; do
-      if [[ ! "$line" =~ ^bats_test_function\  ]]; then
-        continue
-      fi
-      line="${line%$'\r'}"
-      line="${line#* }"
-      TAG_REGEX="--tags '(.*)' (.*)"
-      if [[ "$line" =~ $TAG_REGEX ]]; then
-        IFS=, read -ra tags <<<"${BASH_REMATCH[1]}" || true
-        line="${BASH_REMATCH[2]}"
-      else
-        tags=()
-      fi
-      # is this test focused?
-      if bats_all_in tags 'bats:focus'; then
-        if [[ $focus_mode == 1 ]]; then
-          # focused tests in focus mode should just be registered
-          :
-        else
-          # the current test enables focus mode ...
-          focus_mode=1
-          # ... -> remove previously found, unfocused tests
-          all_tests=()
-          : > "$TESTS_LIST_FILE"
-        fi
-      elif [[ $focus_mode == 1 ]]; then
-        # the current test is not focused but focus mode is enabled -> filter out
-        continue
-        # no else -> unfocused tests outside focus mode should just be registered
-      fi
-      if [[ ${#filter_tags_list[@]} -gt 0 ]]; then
-        local match=
-        for filter_tags in "${filter_tags_list[@]}"; do
-          # empty search tags only match empty test tags!
-          if [[ -z "$filter_tags" ]]; then
-            if [[ ${#tags[@]} -eq 0 ]]; then
-              match=1
-              break
-            fi
-            continue
-          fi
-          local -a positive_filter_tags=() negative_filter_tags=()
-          IFS=, read -ra filter_tags <<<"$filter_tags" || true
-          for filter_tag in "${filter_tags[@]}"; do
-            if [[ $filter_tag == !* ]]; then
-              bats_trim filter_tag "${filter_tag#!}"
-              negative_filter_tags+=("${filter_tag}")
-            else
-              positive_filter_tags+=("${filter_tag}")
-            fi
-          done
-          if bats_append_arrays_as_args positive_filter_tags -- bats_all_in tags &&
-            ! bats_append_arrays_as_args negative_filter_tags -- bats_any_in tags; then
-            match=1
-          fi
-        done
-        if [[ -z "$match" ]]; then
-          continue
-        fi
-      fi
-      test_line=$(printf "%s\t%s" "$filename" "$line")
-      all_tests+=("$test_line")
-      printf "%s\n" "$test_line" >>"$TESTS_LIST_FILE"
-      # avoid unbound variable errors on empty array expansion with old bash versions
-      if [[ ${#test_names[@]} -gt 0 && " ${test_names[*]} " == *" $line "* ]]; then
-        test_dupes+=("$line")
-        continue
-      fi
-      test_names+=("$line")
-    done < <(BATS_TEST_FILTER="$filter" bats-preprocess "$filename")
-
-    if [[ "${#test_dupes[@]}" -ne 0 ]]; then
-      abort "Duplicate test name(s) in file \"${filename}\": ${test_dupes[*]}"
-    fi
-  done
-
-  test_count="${#all_tests[@]}"
-}
 
 TEST_ROOT=${1-}
 TEST_ROOT=${TEST_ROOT%/*}
-BATS_RUN_LOGS_DIRECTORY="$TEST_ROOT/.bats/run-logs"
+export BATS_RUN_LOGS_DIRECTORY="$TEST_ROOT/.bats/run-logs"
 if [[ ! -d "$BATS_RUN_LOGS_DIRECTORY" ]]; then
   if [[ -n "$filter_status" ]]; then
     printf "Error: --filter-status needs '%s/' to save failed tests. Please create this folder, add it to .gitignore and try again.\n" "$BATS_RUN_LOGS_DIRECTORY"
@@ -224,92 +126,21 @@ else
   fi
 fi
 
-bats_gather_tests "$@"
-
-if [[ -n "$filter_status" ]]; then
-  case "$filter_status" in
-  failed)
-    bats_filter_test_by_status() { # <line>
-      ! bats_binary_search "$1" "passed_tests"
-    }
-    ;;
-  passed)
-    bats_filter_test_by_status() {
-      ! bats_binary_search "$1" "failed_tests"
-    }
-    ;;
-  missed)
-    bats_filter_test_by_status() {
-      ! bats_binary_search "$1" "failed_tests" && ! bats_binary_search "$1" "passed_tests"
-    }
-    ;;
-  *)
-    printf "Error: Unknown value '%s' for --filter-status. Valid values are 'failed' and 'missed'.\n" "$filter_status" >&2
-    exit 1
-    ;;
-  esac
-
-  if IFS='' read -d $'\n' -r BATS_PREVIOUS_RUNLOG_FILE < <(ls -1r "$BATS_RUN_LOGS_DIRECTORY"); then
-    BATS_PREVIOUS_RUNLOG_FILE="$BATS_RUN_LOGS_DIRECTORY/$BATS_PREVIOUS_RUNLOG_FILE"
-    if [[ $BATS_PREVIOUS_RUNLOG_FILE == "$BATS_RUNLOG_FILE" ]]; then
-      count=$(find "$BATS_RUN_LOGS_DIRECTORY" -name "$BATS_RUNLOG_DATE*" | wc -l)
-      BATS_RUNLOG_FILE="$BATS_RUN_LOGS_DIRECTORY/${BATS_RUNLOG_DATE}-$count.log"
-    fi
-    failed_tests=()
-    passed_tests=()
-    # store tests that were already filtered out in the last run for the same filter reason
-    last_filtered_tests=()
-    i=0
-    while read -rd $'\n' line; do
-      ((++i))
-      case "$line" in
-      "passed "*)
-        passed_tests+=("${line#passed }")
-        ;;
-      "failed "*)
-        failed_tests+=("${line#failed }")
-        ;;
-      "status-filtered $filter_status"*) # pick up tests that were filtered in the last round for the same status
-        last_filtered_tests+=("${line#status-filtered "$filter_status" }")
-        ;;
-      "status-filtered "*) # ignore other status-filtered lines
-        ;;
-      "#"*) # allow for comments
-        ;;
-      *)
-        printf "Error: %s:%d: Invalid format: %s\n" "$BATS_PREVIOUS_RUNLOG_FILE" "$i" "$line" >&2
-        exit 1
-        ;;
-      esac
-    done < <(sort "$BATS_PREVIOUS_RUNLOG_FILE")
-
-    filtered_tests=()
-    for line in "${all_tests[@]}"; do
-      if bats_filter_test_by_status "$line" && ! bats_binary_search "$line" last_filtered_tests; then
-        printf "%s\n" "$line"
-        filtered_tests+=("$line")
-      else
-        printf "status-filtered %s %s\n" "$filter_status" "$line" >>"$BATS_RUNLOG_FILE"
-      fi
-    done >"$TESTS_LIST_FILE"
-
-    # save filtered tests to exclude them again in next round
-    for test_line in "${last_filtered_tests[@]}"; do
-      printf "status-filtered %s %s\n" "$filter_status" "$test_line"
-    done >>"$BATS_RUNLOG_FILE"
-
-    test_count="${#filtered_tests[@]}"
-    if [[ ${#failed_tests[@]} -eq 0 && ${#filtered_tests[@]} -eq 0 ]]; then
-      printf "There where no failed tests in the last recorded run.\n" >&2
-    fi
-  else
-    printf "No recording of previous runs found. Running all tests!\n" >&2
-  fi
+# create file even if no tests are found so the `read` below won't fail
+touch "$TESTS_LIST_FILE"
+gather_tests_output=$(TESTS_LIST_FILE="$TESTS_LIST_FILE" filter="$filter" filter_status="$filter_status" bats-gather-tests "${gather_tests_flags[@]}" -- "$@")
+test_count=$(grep -c '' "$TESTS_LIST_FILE" || true) # don't fail here when there are no tests
+if [[ $gather_tests_output == focus_mode ]]; then
+  focus_mode=1
+else
+  focus_mode=
 fi
 
 if [[ -n "$count_only_flag" ]]; then
   printf '%d\n' "${test_count}"
-  exit
+  # we don't want to pollute the runlog files, as no tests would have been run
+  [[ $BATS_RUNLOG_FILE != /dev/null ]] && rm "$BATS_RUNLOG_FILE"
+  exit 0
 fi
 
 if [[ -n "$bats_no_parallelize_across_files" ]] && [[ ! "$num_jobs" -gt 1 ]]; then
@@ -392,6 +223,9 @@ bats_run_teardown_suite() {
   # avoid being called twice, in case this is not called through bats_teardown_suite_trap
   # but from the end of file
   trap bats_suite_exit_trap EXIT
+  
+  bats_set_stacktrace_limit
+
   BATS_TEARDOWN_SUITE_COMPLETED=
   teardown_suite >>"$BATS_OUT" 2>&1 || bats_teardown_suite_status=$?
   if ((bats_teardown_suite_status == 0)); then
@@ -426,9 +260,12 @@ if [[ -n "$setup_suite_file" ]]; then
   BATS_TEST_FILENAME="$setup_suite_file"
   # shellcheck source=lib/bats-core/test_functions.bash
   source "$BATS_ROOT/$BATS_LIBDIR/bats-core/test_functions.bash"
+  _bats_test_functions_setup -1 # invalid TEST_NUMBER, as this is not a test
 
   # shellcheck disable=SC1090
   source "$setup_suite_file"
+
+  bats_set_stacktrace_limit
 
   set -eET
   export BATS_SETUP_SUITE_COMPLETED=
