bats_emit_trace: Eliminate $? check
Turns out with the `BASH_COMMAND` and `BATS_LINENO` comparisons, the
value of `$?` is completely irrelevant.

This feature still introduces a very slight decrease in performance for
the existing test suite (before the three new test cases). This is
somewhat unavoidable since we're introducing an extra conditional into
`bats_debug_trap`, the most frequently executed function in the system.

Bash 3.2.57(1)-release before:

  real  0m6.217s
  user  0m3.067s
  sys   0m1.927s

  real  0m6.051s
  user  0m3.070s
  sys   0m1.946s

  real  0m6.135s
  user  0m3.091s
  sys   0m1.997s

Bash 3.2.57(1)-release after:

  real  0m6.131s
  user  0m3.124s
  sys   0m1.982s

  real  0m6.096s
  user  0m3.113s
  sys   0m1.975s

Bash 4.4.23(1)-release before:

  real  0m6.490s
  user  0m3.106s
  sys   0m2.091s

  real  0m6.480s
  user  0m3.097s
  sys   0m2.087s

  real  0m6.513s
  user  0m3.099s
  sys   0m2.106s

Bash 4.4.23(1)-release after:

  real  0m6.529s
  user  0m3.146s
  sys   0m2.096s

  real  0m6.522s
  user  0m3.136s
  sys   0m2.087s

diff --git a/libexec/bats-core/bats-exec-test b/libexec/bats-core/bats-exec-test
--- a/libexec/bats-core/bats-exec-test
+++ b/libexec/bats-core/bats-exec-test
@@ -222,34 +222,30 @@ bats_trim_filename() {
 }
 
 bats_debug_trap() {
-  local status="$?"
-
   if [[ "$BASH_SOURCE" != "$1" ]]; then
     bats_capture_stack_trace
     BATS_LINENO="$BATS_CURRENT_LINENO"
     BATS_CURRENT_LINENO="${BASH_LINENO[0]}"
 
     if [[ -n "$BATS_TRACE" ]]; then
-      bats_emit_trace "$status"
+      bats_emit_trace
     fi
   fi
 }
 
 bats_emit_trace() {
-  local status="$?"
-
   case "$BASH_COMMAND" in
   '"$BATS_TEST_NAME" >> "$BATS_OUT" 2>&1'|'bats_test_begin '*)
     return
     ;;
   esac
 
-  # If `status` is nonzero but the command is the same, then this DEBUG trap
-  # is firing before the ERR trap of a failing command. Since we've printed
+  # If the `BASH_COMMAND` is the same, but `BATS_CURRENT_LINENO` is less than or
+  # equal to `BATS_LINENO` (the previous trap's `BASH_LINENO`), then this DEBUG
+  # trap is firing before the ERR trap of a failing command. Since we've printed
   # the command before it failed, we don't want to print it a second time.
-  if [[ "$status" -eq 0 && \
-        ( "$BASH_COMMAND" != "$BATS_PREVIOUS_COMMAND" || \
-          "$BATS_LINENO" -lt "$BATS_CURRENT_LINENO" ) ]]; then
+  if [[ "$BASH_COMMAND" != "$BATS_PREVIOUS_COMMAND" || \
+        "$BATS_LINENO" -lt "$BATS_CURRENT_LINENO" ]]; then
     local filename="${BASH_SOURCE[2]}"
 
     if [[ "$filename" == "$BATS_TEST_SOURCE" ]]; then
