feat: junit output
- add safe mode and fix violations
- edit `--help` text for consistency
- shfmt

diff --git a/libexec/bats-core/bats b/libexec/bats-core/bats
--- a/libexec/bats-core/bats
+++ b/libexec/bats-core/bats
@@ -17,36 +17,35 @@ usage() {
   local cmd="${0##*/}"
   local line
 
-  while IFS= read -r line; do
-    printf '%s\n' "$line"
-  done <<END_OF_HELP_TEXT
-Usage: $cmd [-cr] [-f <regex>] [-j <jobs>] [-p | -t] <test>...
-       $cmd [-h | -v]
+  cat <<HELP_TEXT_HEADER
+Usage: ${cmd} [OPTIONS] <tests>
+       ${cmd} [-h | -v]
 
-  <test> is the path to a Bats test file, or the path to a directory
-  containing Bats test files (ending with ".bats").
+HELP_TEXT_HEADER
 
-  -c, --count               Count the number of test cases without running any tests
-  -f, --filter              Filter test cases by names matching the regular expression
-  -F, --formatter           Switch between formatters (Default: tap, Options: junit, pretty, tap)
+  cat <<'HELP_TEXT_BODY'
+  <tests> is the path to a Bats test file, or the path to a directory
+  containing Bats test files (ending with ".bats")
+
+  -c, --count               Count test cases without running any tests
+  -f, --filter <regex>      Only run tests that match the regular expression
+  -F, --formatter <type>    Switch between formatters: pretty (default),
+                              tap (default w/o term), junit
   -h, --help                Display this help message
-  -j, --jobs                Number of parallel jobs to run (requires GNU parallel)
-  --parallel-preserve-environment 
-                   Preserve the environment When running via GNU parallel (run 
-                   \`parallel --record-env\` before!)
-  --no-tempdir-cleanup
-                   Prevent bats from deleting the temporary directory that
-                   contains outputs from the test run
-  -o, --output              A directory to output reports to
-  -p, --pretty              [DEPRECATED] Show results in pretty format (default for terminals), use "--formatter pretty" instead
+  -j, --jobs <jobs>         Number of parallel jobs (requires GNU parallel)
+  --parallel-preserve-environment
+                            Preserve the current environment for "--jobs"
+                              (run `parallel --record-env` before)
+  --no-tempdir-cleanup      Preserve test output temporary directory
+  -o, --output <dir>        Directory to write report files
+  -p, --pretty              Shorthand for "--formatter pretty"
   -r, --recursive           Include tests in subdirectories
-  -t, --tap                 [DEPRECATED] Show results in TAP format, use "--formatter tap" instead
-  -T, --timing              Add timing information
+  -t, --tap                 Shorthand for "--formatter tap"
+  -T, --timing              Add timing information to tests
   -v, --version             Display the version number
 
   For more information, see https://github.com/bats-core/bats-core
-
-END_OF_HELP_TEXT
+HELP_TEXT_BODY
 }
 
 expand_link() {
@@ -57,8 +56,7 @@ expand_link() {
   [[ "$1" =~ ^/ ]] || path="."
 
   # Process each component.
-  for part in "${parts[@]}"
-  do
+  for part in "${parts[@]}"; do
     # All components must exist.
     [ -e "$path/$part" ] || return 1
 
@@ -133,56 +131,56 @@ recursive=
 tempdir_cleanup=1
 output=
 if [[ -z "${CI:-}" && -t 0 && -t 1 ]] && command -v tput >/dev/null; then
-	formatter='pretty'
+  formatter='pretty'
 fi
 
 while [[ "$#" -ne 0 ]]; do
   case "$1" in
-	-h | --help)
+  -h | --help)
     version
     usage
     exit 0
     ;;
-	-v | --version)
+  -v | --version)
     version
     exit 0
     ;;
-	-c | --count)
+  -c | --count)
     flags+=('-c')
     ;;
-	-f | --filter)
+  -f | --filter)
     shift
     flags+=('-f' "$1")
     ;;
-	-F | --formatter)
-		shift
-		if [[ $1 =~ ^(pretty|junit|tap)$ ]]; then
-			formatter="$1"
-		else
-			printf "Unknown formatter '%s', valid options are pretty, junit, tap\n" "$1"
-			exit 1
-		fi
-		;;
-	-o | --output)
+  -F | --formatter)
     shift
-		output="$1"
-		;;
-	-p | --pretty)
-		formatter='pretty'
-		;;
-	-j | --jobs)
-		shift
+    if [[ $1 =~ ^(pretty|junit|tap)$ ]]; then
+      formatter="$1"
+    else
+      printf "Unknown formatter '%s', valid options are pretty, junit, tap\n" "$1"
+      exit 1
+    fi
+    ;;
+  -o | --output)
+    shift
+    output="$1"
+    ;;
+  -p | --pretty)
+    formatter='pretty'
+    ;;
+  -j | --jobs)
+    shift
     flags+=('-j' "$1")
     ;;
-	-r | --recursive)
+  -r | --recursive)
     recursive=1
     ;;
-	-t | --tap)
-		formatter='tap'
+  -t | --tap)
+    formatter='tap'
     ;;
-	-T | --timing)
-		flags+=('-T')
-		formatter_flags+=('-T')
+  -T | --timing)
+    flags+=('-T')
+    formatter_flags+=('-T')
     ;;
   --parallel-preserve-environment)
     flags+=("--parallel-preserve-environment")
@@ -215,11 +213,11 @@ if [[ -n "$tempdir_cleanup" ]]; then
 fi
 
 if [[ "$formatter" != "tap" ]]; then
-	flags+=('-x')
+  flags+=('-x')
 fi
 if [[ "$formatter" == "junit" ]]; then
-	flags+=('-T')
-	formatter_flags+=('-T')
+  flags+=('-T')
+  formatter_flags+=('-T')
 fi
 
 if [[ "${#arguments[@]}" -eq 0 ]]; then
@@ -250,6 +248,13 @@ done
 # shellcheck source=lib/bats-core/validator.bash
 source "$BATS_ROOT/lib/bats-core/validator.bash"
 
+if [[ -n "$output" ]]; then
+  if [[ ! -w "${output}" ]]; then
+    printf "Error: output path %s is not writeable\n" "${output}" >&2
+    exit 1
+  fi
+ export BATS_REPORT_OUTPUT_PATH="$output"
+fi
+
 set -o pipefail execfail
-[[ -n "$output" ]] && export BATS_REPORT_OUTPUT_PATH="$output"
-exec bats-exec-suite "${flags[@]}" "${filenames[@]}" | bats_test_count_validator | "bats-format-$formatter" "${formatter_flags[@]}"
+exec bats-exec-suite "${flags[@]}" "${filenames[@]}" | bats_test_count_validator | "bats-format-${formatter}" "${formatter_flags[@]}"
diff --git a/libexec/bats-core/bats-exec-file b/libexec/bats-core/bats-exec-file
--- a/libexec/bats-core/bats-exec-file
+++ b/libexec/bats-core/bats-exec-file
@@ -24,7 +24,7 @@ while [[ "$#" -ne 0 ]]; do
     ;;
   -x)
     flags+=('-x')
-	extended_syntax=1
+    extended_syntax=1
     ;;
   *)
     break
@@ -37,8 +37,8 @@ filename=$1
 TESTS_FILE="$2"
 
 if [[ ! -f "$filename" ]]; then
-    printf 'Testfile "%s" not found\n' "$filename" >&2
-    exit 1
+  printf 'Testfile "%s" not found\n' "$filename" >&2
+  exit 1
 fi
 
 BATS_TEST_FILENAME="$filename"
@@ -49,10 +49,10 @@ source "$BATS_ROOT/lib/bats-core/preprocessing.bash"
 
 bats_run_setup_file() {
   # shellcheck source=lib/bats-core/tracing.bash
-	# shellcheck disable=SC2153
+  # shellcheck disable=SC2153
   source "$BATS_ROOT/lib/bats-core/tracing.bash"
   # shellcheck source=lib/bats-core/test_functions.bash
-	# shellcheck disable=SC2153
+  # shellcheck disable=SC2153
   source "$BATS_ROOT/lib/bats-core/test_functions.bash"
 
   exec 3<&1
@@ -63,7 +63,7 @@ bats_run_setup_file() {
 
   # these are defined only to avoid errors when referencing undefined variables down the line
   # shellcheck disable=2034
-  BATS_TEST_NAME= # used in tracing.bash
+  BATS_TEST_NAME=      # used in tracing.bash
   # shellcheck disable=2034
   BATS_TEST_COMPLETED= # used in tracing.bash
 
@@ -89,7 +89,7 @@ bats_run_teardown_file() {
   trap 'bats_file_exit_trap' EXIT
   local status=0
   # rely on bats_error_trap to catch failures
-  teardown_file >>"$BATS_OUT" 2>&1 
+  teardown_file >>"$BATS_OUT" 2>&1
 
   BATS_TEARDOWN_FILE_COMPLETED=1
 }
@@ -103,35 +103,35 @@ bats_file_teardown_trap() {
 }
 
 bats_file_exit_trap() {
-    trap - ERR EXIT
-    if [[ -z "$BATS_SETUP_FILE_COMPLETED" || -z "$BATS_TEARDOWN_FILE_COMPLETED" ]]; then
-      if [[ -z "$BATS_SETUP_FILE_COMPLETED" ]]; then
-        FAILURE_REASON='setup_file'
-      else 
-        FAILURE_REASON='teardown_file'
-      fi
-		printf "not ok %d %s\n" "$((test_number + 1))" "$FAILURE_REASON failed" >&3
-      bats_print_stack_trace "${BATS_STACK_TRACE[@]}" >&3
-      bats_print_failed_command >&3
-      while IFS= read -r line; do
-          printf "# %s\n" "$line"
-		done <"$BATS_OUT" >&3
-      if [[ -n "$line" ]]; then
-        printf '# %s\n' "$line"
-      fi
-      rm -rf "$BATS_OUT"
-      status=1
+  trap - ERR EXIT
+  if [[ -z "$BATS_SETUP_FILE_COMPLETED" || -z "$BATS_TEARDOWN_FILE_COMPLETED" ]]; then
+    if [[ -z "$BATS_SETUP_FILE_COMPLETED" ]]; then
+      FAILURE_REASON='setup_file'
+    else
+      FAILURE_REASON='teardown_file'
     fi
-    bats_cleanup_preprocessed_source
-    exit $status
+    printf "not ok %d %s\n" "$((test_number + 1))" "$FAILURE_REASON failed" >&3
+    bats_print_stack_trace "${BATS_STACK_TRACE[@]}" >&3
+    bats_print_failed_command >&3
+    while IFS= read -r line; do
+      printf "# %s\n" "$line"
+    done <"$BATS_OUT" >&3
+    if [[ -n "$line" ]]; then
+      printf '# %s\n' "$line"
+    fi
+    rm -rf "$BATS_OUT"
+    status=1
+  fi
+  bats_cleanup_preprocessed_source
+  exit $status
 }
 
-function setup_file() { 
-    return 0 
+function setup_file() {
+  return 0
 }
 
-function teardown_file() { 
-    return 0 
+function teardown_file() {
+  return 0
 }
 
 bats_run_tests() {
@@ -150,8 +150,8 @@ bats_run_tests() {
         test_number=$line_number
       fi
     fi
-    (( ++line_number ))
-  done < "$TESTS_FILE"
+    ((++line_number))
+  done <"$TESTS_FILE"
 
   if [[ "$num_jobs" != 1 ]]; then
     test_pids_and_numbers=()
@@ -182,22 +182,22 @@ bats_run_tests() {
     done
   else
     for test_name in "${tests_to_run[@]}"; do
-        # Only handle non-empty lines
-        if [[ $test_name ]]; then
-            ((++test_number))
-            if [[ "${#flags[@]}" -gt 0 ]]; then
-              bats-exec-test "${flags[@]}" "$filename" "$test_name" "$test_number" || status=1
-            else
-              bats-exec-test "$filename" "$test_name" "$test_number" || status=1
-            fi
+      # Only handle non-empty lines
+      if [[ $test_name ]]; then
+        ((++test_number))
+        if [[ "${#flags[@]}" -gt 0 ]]; then
+          bats-exec-test "${flags[@]}" "$filename" "$test_name" "$test_number" || status=1
+        else
+          bats-exec-test "$filename" "$test_name" "$test_number" || status=1
         fi
+      fi
     done
   fi
   export status
 }
 
 if [[ -n "$extended_syntax" ]]; then
-	printf "suite %s\n" "$(basename $filename)"
+  printf "suite %s\n" "$(basename "$filename")"
 fi
 
 bats_preprocess_source "$filename"
