performance boost: exclude logic improved. find logic debugged and fixed

diff --git a/libexec/bats-core/bats b/libexec/bats-core/bats
--- a/libexec/bats-core/bats
+++ b/libexec/bats-core/bats
@@ -40,9 +40,10 @@ HELP_TEXT_HEADER
                             A two character string of code quote delimiters
                             or 'custom' which requires setting $BATS_BEGIN_CODE_QUOTE and 
                             $BATS_END_CODE_QUOTE. Can also be set via $BATS_CODE_QUOTE_STYLE
-  -e, --exclude <files>     Exclude file(s) from processing. File can also be a directory itself.
-                            <files> are separated by space and enclosed in quotes, 
-                            e.g. `bats --exclude 'foo.bats bar baz qux.bats' [OPTIONS] <tests>`
+  -e, --exclude <files>     Exclude file(s) from processing. File can also be a
+                            directory itself. <files> are separated by space 
+                            and enclosed in quotes, e.g. 
+                            `bats --exclude 'foo.bats bar baz qux.bats' ...`
   -f, --filter <regex>      Only run tests that match the regular expression
   --filter-status <status>  Only run tests with the given status in the last completed (no CTRL+C/SIGINT) run.
                             Valid <status> values are:
@@ -94,6 +95,96 @@ expand_path() {
   printf -v "$result" '%s/%s' "$dirname" "${path##*/}"
 }
 
+# argument: exclude_literal
+is_bats_file() {
+  [[ "$1" == *".bats"* ]]
+}
+
+# argument suite_filename
+is_excluded() {
+  if [[ -z "$exclude_files" ]]; then
+    return 1
+  fi
+  
+  local suite_filename="$1"
+  read -ra EXCLUDE_FILES <<< "$exclude_files"
+
+  for exclude_file in "${EXCLUDE_FILES[@]}"
+  do
+    # 'file check' needed: $exclude_file can contain dir or file filter
+    if is_bats_file "$exclude_file"; then
+      if [[ "$suite_filename" == *"$exclude_file"* ]]; then
+        return 0
+      fi
+    fi
+  done
+
+  return 1
+}
+
+# argument: exclude_literal
+_build_exclude_pattern() {
+  local result="$2"
+  if is_bats_file "$1" ; then
+    printf -v "$result" '%s' "'*$1'" # file matching pattern
+  else
+    printf -v "$result" '%s' "'*/$1/*'" # directory matching pattern
+  fi
+}
+
+# argument: EXCLUDE_FILES
+_build_multi_exclude_pattern() {
+  local result="$2"
+  # given performance concerns we concatenate and loop in a native c-style manner
+  local exclude_pattern
+  _build_exclude_pattern "${EXCLUDE_FILES[0]}" "excl_pattern"
+  exclude_pattern="-path $excl_pattern"
+  local files_length=${#EXCLUDE_FILES[@]}
+  for ((i=1;i<files_length;i++))
+  do
+    _build_exclude_pattern "${EXCLUDE_FILES[i]}" "excl_pattern"
+    exclude_pattern="${exclude_pattern} -o -path $excl_pattern"
+  done
+  printf -v "$result" %s "$exclude_pattern"
+}
+
+# builds and returns specific `find` command as string literal 
+# according given user input to the bat command.
+# 
+# internals: performance over fancy code
+# - using printf -v instead of command substitution for return values
+# - using find combined with -prune instead of piping with grep/awk etc.
+# - use of sub processes limited to the absolute minimum.
+#
+build_find_command_string() {
+  local result="$1"
+  if [[ -z "$exclude_files" ]]; then
+    printf -v "$result" %s \
+      "find -L $filename -type f \
+        -name '*.${BATS_FILE_EXTENSION:-bats}'"
+    return 0
+  fi
+
+  # parsing procedure in terms of performance:
+  # choose array combined with looping (`read -ra`) 
+  # over one liners with grep, sed/awk etc.
+  read -ra EXCLUDE_FILES <<< "$exclude_files"
+
+  if [[ ${#EXCLUDE_FILES[@]} -eq 1 ]]; then
+    _build_exclude_pattern """${EXCLUDE_FILES[0]}""" 'excl_pattern'
+    printf -v "$result" %s \
+      "find -L $filename -type f,d \
+        \( -path $excl_pattern \) \
+        -prune -o -name '*.${BATS_FILE_EXTENSION:-bats}'"
+  else
+    _build_multi_exclude_pattern "${EXCLUDE_FILES[@]}" 'multi_excl_pattern'
+    printf -v "$result" %s \
+      "find -L $filename -type f,d \
+        \( $multi_excl_pattern \) \
+        -prune -o -name '*.${BATS_FILE_EXTENSION:-bats}'"
+  fi
+}
+
 BATS_LIBEXEC="$(cd "$(dirname "$(bats_readlinkf "${BASH_SOURCE[0]}")")"; pwd)"
 export BATS_LIBEXEC
 export BATS_CWD="$PWD"
@@ -118,6 +209,7 @@ arguments=()
 # Unpack single-character options bundled together, e.g. -cr, -pr.
 for arg in "$@"; do
   if [[ "$arg" =~ ^-[^-]. ]]; then
+  #if [[ "$arg" =~ ^-[-]?. ]]; then
     index=1
     while option="${arg:$((index++)):1}"; do
       if [[ -z "$option" ]]; then
@@ -418,88 +510,6 @@ if [[ -n "$setup_suite_file" && ! -f "$setup_suite_file" ]]; then
   abort "--setup-suite-file $setup_suite_file does not exist!"
 fi
 
-# builds and returns specific `find` command as string literal 
-# according given user input to the bat command.
-# 
-# internals: performance over fancy code,
-# use of sub process limited to the absolute minimum.
-#
-_build_find_string() {
-  if [[ -z "$exclude_files" ]]; then
-    printf %s "find -L $filename -type f -name ""*.${BATS_FILE_EXTENSION:-bats}"" -print0"
-    return 0
-  fi
-
-  # parsing procedure in terms of performance:
-  # choose `read -a` combined with looping over one liners with grep, sed/awk etc.
-  read -ra EXCLUDE_FILES <<< "$exclude_files"
-
-  if [[ ${#EXCLUDE_FILES[@]} -eq 1 ]]; then
-    # no additional variable (additional string concatenation), 
-    # make it in once and return immediately!
-    printf %s \
-      "find -L ""$filename"" -type f,d \
-        \( -path $(__build_exclude_pattern "${EXCLUDE_FILES[0]}") \) \
-        -prune -o -name "*."${BATS_FILE_EXTENSION:-bats}"" -print -print0"
-    return 0
-  else
-    printf %s \
-      "find -L ""$filename"" -type f,d \
-        \( $(__build_multi_exclude_pattern "${EXCLUDE_FILES[@]}") \) \
-        -prune -o -name "*."${BATS_FILE_EXTENSION:-bats}"" -print -print0"
-    return 0
-  fi
-}
-
-# argument: exclude_literal
-__is_bats_file() {
-  [[ "$1" == *".bats"* ]]
-}
-
-# argument suite_filename
-_is_excluded() {
-  if [[ -z "$exclude_files" ]]; then
-    return 1
-  fi
-  
-  local suite_filename="$1"
-  read -ra EXCLUDE_FILES <<< "$exclude_files"
-
-  for exclude_file in "${EXCLUDE_FILES[@]}"
-  do
-    # 'double check' needed: $exclude_file can contain dir or file filter
-    if __is_bats_file "$exclude_file"; then
-      if [[ "$suite_filename" == *"$exclude_file"* ]]; then
-        return 0
-      fi
-    fi
-  done
-
-  return 1
-}
-
-# argument: exclude_literal
-__build_exclude_pattern() {
-  if __is_bats_file "$1" ; then
-    printf %s "*$1" # file matching pattern
-  else
-    printf %s "*/$1/*" # directory matching pattern
-  fi
-}
-
-# argument: EXCLUDE_FILES
-__build_multi_exclude_pattern() {
-  # given performance concerns we concatenate and loop in a native c-style manner
-  local exclude_pattern
-  exclude_pattern="-path $(__build_exclude_pattern "${EXCLUDE_FILES[0]}")"
-  local files_length=${#EXCLUDE_FILES[@]}
-  for ((i=1;i<files_length;i++))
-  do
-    exclude_pattern="${exclude_pattern} -o -path $(__build_exclude_pattern "${EXCLUDE_FILES[i]}")"
-  done
-  echo "$exclude_pattern"
-}
-
 filenames=()
 for filename in "${arguments[@]}"; do
   expand_path "$filename" 'filename'
@@ -519,12 +529,18 @@ for filename in "${arguments[@]}"; do
   if [[ -d "$filename" ]]; then
     shopt -s nullglob
     if [[ "$recursive" -eq 1 ]]; then
+      build_find_command_string "find_command"
+
       while IFS= read -r -d $'\0' file; do
-        filenames+=("$file")
-      done < <(eval "$(_build_find_string)" | sort -z)
+        filenames+=("$file")    
+        # process substitution and redirecting in use; 
+        # => pipe [<(..)] and redirect [<] '$find_command' to standard input
+        # for `read` using C-Style string termination '\0' [-print0]
+        # eval is a built-in command, no performance issue's expected
+      done < <(eval "$find_command" -print0 | sort -z)
     else
       for suite_filename in "$filename"/*."${BATS_FILE_EXTENSION:-bats}"; do
-        if ! _is_excluded "$suite_filename" ; then
+        if ! is_excluded "$suite_filename" ; then
           filenames+=("$suite_filename")
         fi
       done
