Show teardown() errors when EXIT trap fires
This enables Bats to report errors in `teardown()` due to one of its
commands triggering the EXIT trap without setting `$?` properly. This is
accomplished by calling `bats_teardown_trap` manually whenever the test
case (including `setup()`) runs to completion, i.e. whenever the test
case doesn't trigger an error that triggers the EXIT trap.

This will break down when both the test case (including `setup()`) _and_
`teardown()` trigger errors that both trigger the EXIT trap, because a
running EXIT trap cannot trigger another EXIT trap by design. In this
case, `bats_exit_trap` will not get called, truncating the test output.

diff --git a/libexec/bats-exec-test b/libexec/bats-exec-test
--- a/libexec/bats-exec-test
+++ b/libexec/bats-exec-test
@@ -229,11 +229,14 @@ bats_debug_trap() {
   fi
 }
 
-# When running under Bash 3.2.57(1)-release on macOS, the `ERR` trap may not
-# always fire, but the `EXIT` trap will. For this reason we call it at the very
-# beginning of `bats_teardown_trap` (the `DEBUG` trap for the call will move
-# `BATS_CURRENT_STACK_TRACE` to `BATS_PREVIOUS_STACK_TRACE`) and check the value
-# of `$?` before taking other actions.
+# For some versions of Bash, the `ERR` trap may not always fire for every
+# command failure, but the `EXIT` trap will. For this reason we call it at the
+# very beginning of `bats_teardown_trap` (the `DEBUG` trap for the call will
+# move `BATS_CURRENT_STACK_TRACE` to `BATS_PREVIOUS_STACK_TRACE`) and check the
+# value of `$?` before taking other actions.
+#
+# See `bats_exit_trap` for an additional EXIT error handling case when `$?`
+# isn't set properly.
 bats_error_trap() {
   local status="$?"
   if [[ "$status" -ne '0' ]]; then
@@ -245,7 +248,6 @@ bats_error_trap() {
 
 bats_teardown_trap() {
   bats_error_trap
-  trap "bats_exit_trap" exit
   local status=0
   teardown >>"$BATS_OUT" 2>&1 || status="$?"
 
@@ -273,8 +275,11 @@ bats_exit_trap() {
 
   if [ -z "$BATS_TEST_COMPLETED" ] || [ -z "$BATS_TEARDOWN_COMPLETED" ]; then
     if [[ "${#BATS_ERROR_STACK_TRACE[@]}" -eq 0 ]]; then
-      # Some Bash command failures trigger the EXIT trap, but not ERR.
-      BATS_ERROR_STACK_TRACE=( "${BATS_CURRENT_STACK_TRACE[@]}" )
+      # For some versions of bash, `$?` may not be set properly for some error
+      # conditions before triggering the EXIT trap directly (see #72 and #81).
+      # Thanks to the `BATS_TEST_COMPLETED` and `BATS_TEARDOWN_COMPLETED`
+      # signals, this will pinpoint such errors.
+      BATS_ERROR_STACK_TRACE=( "${BATS_PREVIOUS_STACK_TRACE[@]}" )
       BATS_ERROR_STATUS=1
     fi
     echo "not ok $BATS_TEST_NUMBER $BATS_TEST_DESCRIPTION" >&3
@@ -318,6 +323,8 @@ bats_perform_test() {
     trap "bats_teardown_trap" exit
     "$BATS_TEST_NAME" >>"$BATS_OUT" 2>&1
     BATS_TEST_COMPLETED=1
+    trap "bats_exit_trap" exit
+    bats_teardown_trap
 
   else
     echo "bats: unknown test name \`$BATS_TEST_NAME'" >&2
